package ee.schimke.composeai.cli.serve.icons

import java.io.File
import java.security.MessageDigest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Assumptions.assumeTrue

/**
 * Regenerates the legacy-migration fixtures from their two pinned inputs, and audits them.
 *
 * The fixtures are large enough that a reader has to be able to reproduce them rather than trust
 * them, and a pin bump has to be a command rather than a morning's work. Both inputs live outside
 * the repository on purpose — the Material Symbols code point list is pinned source data the server
 * fetches into its cache, and the Material Icons inventory is a build output — so they are named on
 * the command line:
 * ```
 * ./gradlew generateMaterialIconInventory
 * ./gradlew :server:test --tests '*LegacyIconNamesFixture*' \
 *   -Dcomposeai.materialSymbols.codePoints=$PWD/<ui-builder-dir>/material-symbols/symbols.codepoints \
 *   -Dcomposeai.materialIcons.inventory=$PWD/build/generated/materialIcons/material-icon-inventory.tsv
 * ```
 *
 * **Absolute paths**: a test runs with its own project as the working directory, so a
 * repository-root path like `build/generated/…` would resolve under `server/` and find nothing.
 * Pass neither property and regeneration is skipped while the audit below still runs, which is what
 * CI does. Pass one that does not resolve and it fails rather than skips — a regeneration that
 * quietly did nothing and reported success is the failure this command exists to prevent.
 *
 * Regeneration goes through [MaterialSymbolsLegacyKeys] itself rather than restating its rules, so
 * the fixture cannot drift from the code by being produced by a second implementation of it.
 */
class LegacyIconNamesFixtureTest {

  private val resources = File("src/test/resources/material-symbols")

  /**
   * The file a system property names, or null when the property is absent.
   *
   * A property that is set but does not resolve throws rather than returning null: that is the
   * difference between "CI, which passes neither" and "somebody ran the documented command with a
   * path relative to the wrong directory", and the second must not look like the first.
   */
  private fun property(name: String): File? =
    System.getProperty(name)?.let(::File)?.also {
      check(it.isFile) {
        "-D$name=$it does not resolve; the working directory is ${File("").absolutePath}, " +
          "so pass an absolute path"
      }
    }

  @Test
  fun `regenerates the fixtures when both pinned inputs are named`() {
    val codePoints = property("composeai.materialSymbols.codePoints")
    val inventory = property("composeai.materialIcons.inventory")
    assumeTrue(
      codePoints != null && inventory != null,
      "pass -Dcomposeai.materialSymbols.codePoints and -Dcomposeai.materialIcons.inventory to regenerate",
    )
    val raw = codePoints!!.readBytes()
    val digest =
      MessageDigest.getInstance("SHA-256").digest(raw).joinToString("") { "%02x".format(it) }
    val names =
      raw
        .decodeToString()
        .lineSequence()
        .filter(String::isNotBlank)
        .map { it.split(" ")[0] }
        .toList()
    val known: (String) -> Boolean = names.toSet()::contains

    val keys =
      inventory!!
        .readLines()
        .filter { it.isNotBlank() && !it.startsWith("#") }
        .map { it.split('\t')[0] }
    val members = keys.filter { '/' in it }.map { it.substringAfterLast('/') }.distinct().sorted()
    val aliases = keys.filterNot { '/' in it }.sorted()

    resources.mkdirs()
    File(resources, "symbol-names.txt")
      .writeText(
        "# The names the pinned Material Symbols Outlined face carries. Test scope only: the\n" +
          "# server reads the real code point list from its own cache.\n" +
          "# code-point-list SHA-256 $digest\n" +
          names.joinToString("\n", postfix = "\n")
      )
    File(resources, "legacy-icon-names.tsv")
      .writeText(
        buildString {
          append("# Every Material Icons member name the shipped catalog qualifies with a style,\n")
          append("# and the Material Symbols name it migrates to. An empty target means the icon\n")
          append("# has no Symbols equivalent. Generated by LegacyIconNamesFixtureTest; see its\n")
          append("# KDoc for the command that reproduces it.\n")
          append("# code-point-list SHA-256 $digest\n")
          members.forEach { member ->
            val target =
              when (val result = MaterialSymbolsLegacyKeys.migrate("filled/$member", known)) {
                is LegacyIconMigration.Migrated -> result.name
                else -> ""
              }
            append(member).append('\t').append(target).append('\n')
          }
        }
      )
    File(resources, "legacy-icon-aliases.tsv")
      .writeText(
        buildString {
          append("# The unqualified compatibility keys the catalog issued before it carried\n")
          append("# styles, and the qualified key each one actually stood for, read from the\n")
          append(
            "# inventory's own `Icons member` column. Generated by LegacyIconNamesFixtureTest.\n"
          )
          val members =
            inventory
              .readLines()
              .filter { it.isNotBlank() && !it.startsWith("#") }
              .map { it.split('\t') }
              .filterNot { '/' in it[0] }
              .associate { it[0] to it[2] }
          aliases.forEach { append(it).append('\t').append(members.getValue(it)).append('\n') }
        }
      )
  }

  @Test
  fun `the fixtures agree with each other`() {
    // Cheap, and it catches the way these go wrong: a regeneration that half-ran, or a hand edit.
    fun rows(name: String) =
      File(resources, name).readLines().filter { it.isNotBlank() && !it.startsWith("#") }

    val names = rows("symbol-names.txt").toSet()
    val targets = rows("legacy-icon-names.tsv").map { it.split('\t') }
    assertTrue(targets.all { it.size == 2 }, "every mapping row is name and target")
    val absent = targets.map { it[1] }.filter { it.isNotEmpty() && it !in names }
    assertTrue(absent.isEmpty(), "targets the pinned face does not carry: $absent")

    val digests =
      listOf("symbol-names.txt", "legacy-icon-names.tsv").map { file ->
        File(resources, file)
          .readLines()
          .first { it.startsWith("# code-point-list SHA-256 ") }
          .substringAfterLast(' ')
      }
    assertEquals(
      1,
      digests.distinct().size,
      "the two fixtures were generated against different code point lists: $digests",
    )
  }
}
