#!/usr/bin/env bash
# Guard: .env.example stays a COMPLETE menu of the compose file's variables, and carries no secrets.
#
# Two failures this prevents, both quiet.
#
# **A secret reaching the repository.** This file is generated by copying a real box's .env and
# substituting placeholders, which is exactly the workflow that leaks a token the day someone adds
# a variable whose name the substitution list does not know about. So the check is not "did we
# remember" — it is a property of the file: every secret-named key must hold a `replace-me` value,
# and no value anywhere may look like a credential.
#
# **Drifting out of sync with the compose file.** The file's whole value is that it lists every knob
# with the default that already applies, so an operator can uncomment rather than hunt through
# README. A variable added to docker-compose.yml and not here is invisible; one removed from the
# compose file and left here is advice that silently does nothing.
#
# Static: no Docker, no network, no secrets required.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
example="${ENV_EXAMPLE_FILE:-${here}/.env.example}"
compose="${COMPOSE_FILE_UNDER_TEST:-${here}/docker-compose.yml}"

for f in "${example}" "${compose}"; do
  [[ -f "${f}" ]] || { echo "FAIL: missing ${f}" >&2; exit 1; }
done

fail=0
note() { echo "FAIL: $*" >&2; fail=1; }

# Every ${VAR} the compose file interpolates.
mapfile -t compose_vars < <(
  grep -oE '\$\{[A-Za-z_][A-Za-z0-9_]*' "${compose}" | sed 's/^\${//' | sort -u
)
((${#compose_vars[@]})) || { echo "FAIL: found no variables in ${compose##*/} — the detector is broken." >&2; exit 1; }

# Every key the example declares, active or commented.
mapfile -t example_keys < <(
  grep -oE '^[[:space:]]*#?[[:space:]]*[A-Za-z_][A-Za-z0-9_]*=' "${example}" |
    tr -d ' #' | sed 's/=$//' | sort -u
)

for v in "${compose_vars[@]}"; do
  grep -qx -- "${v}" <<<"$(printf '%s\n' "${example_keys[@]}")" ||
    note "${v} is read by ${compose##*/} but absent from .env.example — the menu is incomplete."
done
for k in "${example_keys[@]}"; do
  grep -qx -- "${k}" <<<"$(printf '%s\n' "${compose_vars[@]}")" ||
    note "${k} is in .env.example but no longer read by ${compose##*/} — stale advice."
done

# No secrets. Checked as a property of the values, not against a list of known key names.
while IFS= read -r line; do
  key="${line%%=*}"; value="${line#*=}"
  [[ -n "${value}" ]] || continue
  if [[ "${key}" =~ (TOKEN|SECRET|PASSWORD|CREDENTIAL|API_?KEY|CLIENT_ID) ]]; then
    [[ "${value}" == replace-me* ]] ||
      note "${key} holds a real-looking value; every secret-named key must be a 'replace-me' placeholder."
  fi
  # A long, mixed-case-and-digit, punctuation-free run is what a generated token looks like.
  if [[ ${#value} -ge 24 && "${value}" =~ ^[A-Za-z0-9+/=_-]+$ &&
        "${value}" =~ [A-Z] && "${value}" =~ [a-z] && "${value}" =~ [0-9] &&
        "${value}" != replace-me* ]]; then
    note "${key} holds a ${#value}-char high-entropy value — that looks like a credential."
  fi
done < <(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "${example}")

((fail)) && exit 1
echo "OK: .env.example covers ${#compose_vars[@]} compose variables and carries no secrets."
