package ee.schimke.composeai.cli.serve

import ee.schimke.composeai.discovery.ComponentRecord
import ee.schimke.composeai.discovery.ComponentRecordFile
import ee.schimke.composeai.uibuilder.export.RecordFreeExport
import ee.schimke.composeai.uibuilder.export.UiBuilderBuildFeatures
import ee.schimke.composeai.uibuilder.export.UiBuilderCatalogPlatform
import ee.schimke.composeai.uibuilder.export.UiBuilderDocument
import ee.schimke.composeai.uibuilder.export.helloWidgetUiBuilderDocument
import ee.schimke.composeai.uibuilder.export.toDesignDocumentV1
import ee.schimke.composeai.uibuilder.export.wearScreenUiBuilderDocument
import ee.schimke.composeai.uibuilder.protocol.AnimationStateV1
import ee.schimke.composeai.uibuilder.protocol.CatalogBenchmarkV1
import ee.schimke.composeai.uibuilder.protocol.CatalogCapabilityV1
import ee.schimke.composeai.uibuilder.protocol.CatalogReferenceV1
import ee.schimke.composeai.uibuilder.protocol.DesignDocumentV1
import ee.schimke.composeai.uibuilder.protocol.DesignEnvironmentV1
import ee.schimke.composeai.uibuilder.protocol.ExportCapabilitiesV1
import ee.schimke.composeai.uibuilder.protocol.ExportEncodingV1
import ee.schimke.composeai.uibuilder.protocol.ExportFormatV1
import ee.schimke.composeai.uibuilder.protocol.LayoutDirectionV1
import ee.schimke.composeai.uibuilder.protocol.ThemeV1
import ee.schimke.composeai.uibuilder.protocol.WindowPostureV1
import ee.schimke.composeai.uibuilder.service.AuthenticatedUiBuilderActor
import ee.schimke.composeai.uibuilder.service.PublishedUiBuilderCatalog
import ee.schimke.composeai.uibuilder.service.RevisionPinnedUiBuilderExport
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.encodeToJsonElement

/**
 * Export for designs with no component record: `remote-m3` and `wear-m3` have their own emitters
 * (Remote Compose widgets in a `WearWidgetDocument`; `ScreenScaffold`'s scroll state matches no
 * recovered signature). Asserted with a deliberately unconfigured record source, matching
 * deployments that pass a record for `m3-catalog` only.
 */
class RecordFreeComposeExportTest {

  private val executor =
    ScreenGeneratorComposeExportExecutor(
      { ComponentRecordSource.Lookup.Unconfigured },
      PACKAGE_NAME,
    )

  @Test
  fun `a wear widget design exports as a file, with a package and no diagnostic`() {
    val artifact = export(widget())

    assertEquals(emptyList(), artifact.diagnostics)
    assertEquals(ExportFormatV1.COMPOSE, artifact.format)
    assertEquals("text/x-kotlin; charset=utf-8", artifact.mediaType)
    assertEquals(ExportEncodingV1.UTF8, artifact.encoding)
    // Provenance first, then the file annotation Kotlin requires before the package, then the
    // package the Code pane's snippet deliberately does not carry.
    assertTrue(
      artifact.content.startsWith("// Generated by compose-preview serve"),
      artifact.content,
    )
    assertTrue(
      "@file:Suppress(\"RestrictedApi\")\n\npackage $PACKAGE_NAME\n" in artifact.content,
      artifact.content,
    )
    // It is the widget's own source, not a Material 3 screen's.
    assertTrue("class HelloWidget : GlanceWearWidget()" in artifact.content, artifact.content)
    assertTrue("@RemoteComposable" in artifact.content, artifact.content)
    // The scaffold is erased as the Code pane does: on-device the launcher draws the widget
    // container, so naming it would draw a second frame.
    assertFalse("widget-container" in artifact.content, artifact.content)
    assertFalse("WearWidgetContainer" in artifact.content, artifact.content)
    // What the container's background becomes instead: the widget's own brush, which is what the
    // host paints the squircle with.
    assertTrue(
      "WearWidgetDocument(background = WearWidgetBrush.color(colorScheme.primary))" in
        artifact.content,
      artifact.content,
    )
    // Its size selects the preview params providers (one footprint each) rather than a dimension;
    // the rectangular render is the one recommended for the widget picker.
    assertTrue(
      "SquircleSmallWidgetPreviewParams().values.maxBy { it.widthDp }" in artifact.content,
      artifact.content,
    )
    assertTrue(
      "RectangularSmallWidgetPreviewParams().values.maxBy { it.widthDp }" in artifact.content,
      artifact.content,
    )
    // Provenance names the pinned revision and catalog, as the record-driven export does.
    assertTrue("Design widget-1 revision 0" in artifact.content, artifact.content)
    assertTrue("Catalog remote-m3@candidate" in artifact.content, artifact.content)
  }

  @Test
  fun `a wear screen design exports the same way`() {
    val artifact = export(wearScreen())

    assertEquals(emptyList(), artifact.diagnostics)
    assertTrue("package $PACKAGE_NAME\n" in artifact.content, artifact.content)
    assertTrue("@WearPreviewDevices" in artifact.content, artifact.content)
  }

  @Test
  fun `the same design generates different source for the native preview lane`() {
    // Two files from one design: the export above is what a designer pastes; this is what the host
    // compiles to draw it (body, brush, container spec, no `GlanceWearWidget`).
    val generated =
      executor.generate(widget()) as ScreenGeneratorComposeExportExecutor.Generated.Emitted

    assertEquals("HelloWidget", generated.screenName)
    assertTrue("fun HelloWidgetContent() {" in generated.source, generated.source)
    assertTrue(
      "fun HelloWidgetBackground(): WearWidgetBrush {" in generated.source,
      generated.source,
    )
    assertTrue("fun HelloWidgetParams(): WearWidgetParams =" in generated.source, generated.source)
    assertFalse("GlanceWearWidget" in generated.source, generated.source)
    assertFalse("WearWidgetPreviewParams" in generated.source, generated.source)
    // The current Small host frame, including its own padding, rather than the design environment,
    // which describes a watch screen. This follows the UI-builder exporter version the server pins.
    assertEquals(
      ScreenGeneratorComposeExportExecutor.Generated.WidgetFrame(224, 84),
      generated.widgetFrame,
    )
  }

  @Test
  fun `a legacy padding override renders in the predefined host frame`() {
    // Only the predefined host shapes are supported: a design saved while padding was authorable
    // still carries it, but the native lane builds the selected shape's own params and ignores it.
    val generated =
      executor.generate(widget(horizontalPaddingDp = 20.0))
        as ScreenGeneratorComposeExportExecutor.Generated.Emitted

    assertFalse("horizontalPaddingDp = 20f" in generated.source, generated.source)
    assertEquals(
      ScreenGeneratorComposeExportExecutor.Generated.WidgetFrame(224, 84),
      generated.widgetFrame,
    )
  }

  @Test
  fun `a legacy padding override no longer refuses the export`() {
    // Nothing draws the override any more, so there is no frame for a generated preview to
    // disagree with, and the export writes the widget like any other.
    val artifact = export(widget(horizontalPaddingDp = 20.0))

    assertEquals(emptyList(), artifact.diagnostics)
    assertTrue("class HelloWidget : GlanceWearWidget()" in artifact.content, artifact.content)
  }

  @Test
  fun `an ordinary screen is left to the record-driven generator`() {
    assertNull(RecordFreeExport.generate(ScreenGeneratorScreenFixture.document()))
    // And the executor still refuses it for the reason it always did, rather than for this one.
    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.NO_COMPONENT_RECORD),
      export(ScreenGeneratorScreenFixture.document()).diagnostics.map { it.code },
    )
  }

  @Test
  fun `an arbitrary Remote catalog exports ordinary roots using its declared platform`() {
    org.junit.jupiter.api.Assumptions.assumeTrue(
      UiBuilderBuildFeatures.remoteCompose,
      "Enable with -PuiBuilderRemoteCompose=true",
    )
    val original =
      json.decodeFromString<DesignDocumentV1>(
        java.io
          .File("../docs/design/evidence/ui-builder-live-document-preview/sample.document.json")
          .readText()
      )
    val document = original.copy(catalogPin = original.catalogPin.copy(systemId = "custom-remote"))
    val capabilities =
      catalog
        .newBuilder()
        .also {
          it.statusSemantics = JsonObject(mapOf("platform" to JsonPrimitive("remote-compose")))
        }
        .build()
    val artifact = export(document, capabilities)
    assertTrue(artifact.diagnostics.isEmpty(), artifact.diagnostics.toString())
    assertTrue("RemoteStateLayout" in artifact.content, artifact.content)
    assertTrue(".clickable(valueChange(page, 20.ri))" in artifact.content, artifact.content)
    assertFalse("WearWidget" in artifact.content, artifact.content)
  }

  /**
   * `remote-m3/remote-text` names the fixed Remote Material 3 API, not a discovered pack call; once
   * catalog validation accepts it, both export lanes emit `RemoteText` without a component record.
   * The published half proves adding a record doesn't change that.
   */
  @Test
  fun `remote text exports as a fixed API with or without a published component record`() {
    val design = widgetAroundRemoteText()

    val unpublished = export(design)
    assertEquals(emptyList(), unpublished.diagnostics, unpublished.content)
    assertTrue("RemoteText(" in unpublished.content, unpublished.content)

    val artifact =
      publishedExecutor.export(
        RevisionPinnedUiBuilderExport(
          actor = AuthenticatedUiBuilderActor("tester"),
          designId = design.id,
          revision = design.revision,
          documentHash = "hash",
          document = design,
          catalog = catalog,
          format = ExportFormatV1.COMPOSE,
        )
      )

    assertEquals(emptyList(), artifact.diagnostics, artifact.content)
    assertTrue("RemoteText(" in artifact.content, artifact.content)
    assertTrue("text = \"Hello\".rs" in artifact.content, artifact.content)

    // The native preview exporter is a third lane with its own emitter; it must agree with the file
    // export.
    val preview =
      publishedExecutor.generate(design) as ScreenGeneratorComposeExportExecutor.Generated.Emitted
    assertTrue("RemoteText(" in preview.source, preview.source)
    val unpublishedPreview =
      executor.generate(design) as ScreenGeneratorComposeExportExecutor.Generated.Emitted
    assertTrue("RemoteText(" in unpublishedPreview.source, unpublishedPreview.source)
  }

  /**
   * Published catalog components are version-checked like every other record:
   * `ComponentRecordSource` tolerates newer schemas for the shelf, but generating from one must
   * refuse by version.
   */
  @Test
  fun `a published catalog on a schema this build will not generate from refuses by version`() {
    val ahead =
      ScreenGeneratorComposeExportExecutor(
        {
          ComponentRecordSource.Lookup.Found(
            remoteM3Record.newBuilder().apply { schemaVersion = 99 }.build()
          )
        },
        PACKAGE_NAME,
        publishedComponents = { publishedRemoteM3 },
      )

    val artifact =
      ahead.export(
        RevisionPinnedUiBuilderExport(
          actor = AuthenticatedUiBuilderActor("tester"),
          designId = widgetAroundRemoteText().id,
          revision = widgetAroundRemoteText().revision,
          documentHash = "hash",
          document = widgetAroundRemoteText(),
          catalog = catalog,
          format = ExportFormatV1.COMPOSE,
        )
      )

    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.NO_COMPONENT_RECORD),
      artifact.diagnostics.map { it.code },
      artifact.content,
    )
    assertTrue("is schema 99" in artifact.diagnostics.single().message)
  }

  @Test
  fun `the record-free catalogs are the two that ship without a record`() {
    assertEquals(setOf("remote-m3", "wear-m3"), RecordFreeExport.CATALOG_SYSTEM_IDS)
  }

  /**
   * What `remote-m3` composes to on a host that reads its published file, built by the same call
   * `ServeRunner` makes.
   */
  private val remoteM3Record: ComponentRecordFile by lazy {
    json.decodeFromString(
      java.io.File("../docs/design/fixtures/ui-builder/remote-m3-record-v1.json").readText()
    )
  }

  private val publishedRemoteM3: Map<String, ComponentRecord> by lazy {
    val fixtures = java.io.File("../docs/design/fixtures/ui-builder")
    val record = remoteM3Record
    val composed =
      PublishedUiBuilderCatalog.compose(
        fixtures.resolve("remote-m3-published-v1.json").readText(),
        record,
        ExportCapabilitiesV1.Builder()
          .also {
            it.composeCode = true
            it.svg = false
            it.png = false
          }
          .build(),
      )
    assertTrue(composed is PublishedUiBuilderCatalog.Result.Composed, composed.toString())
    (composed as PublishedUiBuilderCatalog.Result.Composed).records
  }

  /** The executor as a host serving the published `remote-m3` catalog builds it. */
  private val publishedExecutor by lazy {
    ScreenGeneratorComposeExportExecutor(
      { ComponentRecordSource.Lookup.Unconfigured },
      PACKAGE_NAME,
      publishedComponents = { systemId ->
        if (systemId == "remote-m3") publishedRemoteM3 else emptyMap()
      },
    )
  }

  /** The Hello widget with its text swapped for the catalog's own `RemoteText`. */
  private fun widgetAroundRemoteText(): DesignDocumentV1 {
    val document = helloWidgetUiBuilderDocument("widget-1", pin("remote-m3"), environment)
    val text = document.nodes.getValue("hello-text")
    return document
      .copy(
        nodes =
          document.nodes +
            ("hello-text" to
              text.copy(
                componentId = "remote-m3/remote-text",
                properties =
                  JsonObject(
                    mapOf(
                      "text" to json.parseToJsonElement("""{"type":"string","value":"Hello"}""")
                    )
                  ),
              ))
      )
      .toDesignDocumentV1()
  }

  @Test
  fun `bound row callbacks reach the revision pinned service export unchanged`() {
    org.junit.jupiter.api.Assumptions.assumeTrue(
      UiBuilderBuildFeatures.remoteCompose,
      "Enable with -PuiBuilderRemoteCompose=true",
    )
    val document =
      json.decodeFromString<UiBuilderDocument>(
        java.io.File("../experiments/remote-state-selection/bound-actions.document.json").readText()
      )
    val expected =
      assertIs<RecordFreeExport.Generated.Emitted>(
          RecordFreeExport.generate(document, UiBuilderCatalogPlatform.REMOTE_COMPOSE, PACKAGE_NAME)
        )
        .source
    val remote =
      catalog
        .newBuilder()
        .also {
          it.statusSemantics = JsonObject(mapOf("platform" to JsonPrimitive("remote-compose")))
        }
        .build()
    val artifact = export(document.toDesignDocumentV1(), remote)
    assertEquals(emptyList(), artifact.diagnostics)
    assertTrue(artifact.content.endsWith(expected), artifact.content)
    assertTrue("Design bound-actions-proof revision 0" in artifact.content)
  }

  private fun export(document: DesignDocumentV1, capabilities: CatalogCapabilityV1 = catalog) =
    executor.export(
      RevisionPinnedUiBuilderExport(
        actor = AuthenticatedUiBuilderActor("tester"),
        designId = document.id,
        revision = document.revision,
        documentHash = "hash",
        document = document,
        catalog = capabilities,
        format = ExportFormatV1.COMPOSE,
      )
    )

  /** The Hello sample, optionally with a padding the widget host does not let a design choose. */
  private fun widget(horizontalPaddingDp: Double? = null): DesignDocumentV1 {
    val document =
      helloWidgetUiBuilderDocument("widget-1", pin("remote-m3"), environment).let { design ->
        if (horizontalPaddingDp == null) return@let design
        val rootId = design.roots.single()
        val root = design.nodes.getValue(rootId)
        design.copy(
          nodes =
            design.nodes +
              (rootId to
                root.copy(
                  properties =
                    JsonObject(
                      root.properties +
                        ("horizontalPaddingDp" to
                          json.parseToJsonElement(
                            """{"type":"float","value":$horizontalPaddingDp}"""
                          ))
                    )
                ))
        )
      }
    return document.toDesignDocumentV1()
  }

  private fun wearScreen(): DesignDocumentV1 =
    wearScreenUiBuilderDocument("screen-1", pin("wear-m3"), environment).toDesignDocumentV1()

  private fun pin(systemId: String): JsonObject =
    json
      .encodeToJsonElement(
        CatalogReferenceV1(
          systemId = systemId,
          catalogRevision = "candidate",
          capabilityDigest = "candidate",
          nativeRuntimeId = "candidate",
        )
      )
      .let { it as JsonObject }

  private val environment: JsonObject =
    json
      .encodeToJsonElement(
        DesignEnvironmentV1(
          widthDp = 216,
          heightDp = 76,
          density = 1.0,
          theme = ThemeV1.DARK,
          locale = "en-US",
          fontScale = 1.0,
          layoutDirection = LayoutDirectionV1.LTR,
          windowPosture = WindowPostureV1.FLAT,
          animations = AnimationStateV1.SETTLED,
          networkAccess = false,
        )
      )
      .let { it as JsonObject }

  private val catalog =
    CatalogCapabilityV1.Builder(
        "compose-catalog-capabilities/v1",
        CatalogBenchmarkV1.Builder("test", "source", "remote-m3", "candidate", "candidate").build(),
        emptyList(),
      )
      .also {
        it.exportCapabilities =
          ExportCapabilitiesV1.Builder()
            .also {
              it.composeCode = true
              it.svg = false
              it.png = false
            }
            .build()
      }
      .build()

  private companion object {
    const val PACKAGE_NAME = "generated.uibuilder"

    val json = Json {
      classDiscriminator = "type"
      encodeDefaults = true
      explicitNulls = false
      ignoreUnknownKeys = true
    }
  }
}
