package ee.schimke.composeai.cli.serve

import ee.schimke.composeai.uibuilder.RecordFreeExport
import ee.schimke.composeai.uibuilder.helloWidgetUiBuilderDocument
import ee.schimke.composeai.uibuilder.protocol.AnimationStateV1
import ee.schimke.composeai.uibuilder.protocol.CatalogBenchmarkV1
import ee.schimke.composeai.uibuilder.protocol.CatalogCapabilityV1
import ee.schimke.composeai.uibuilder.protocol.CatalogReferenceV1
import ee.schimke.composeai.uibuilder.protocol.DesignDocumentV1
import ee.schimke.composeai.uibuilder.protocol.DesignEnvironmentV1
import ee.schimke.composeai.uibuilder.protocol.ExportCapabilitiesV1
import ee.schimke.composeai.uibuilder.protocol.ExportEncodingV1
import ee.schimke.composeai.uibuilder.protocol.ExportFormatV1
import ee.schimke.composeai.uibuilder.protocol.LayoutDirectionV1
import ee.schimke.composeai.uibuilder.protocol.ThemeV1
import ee.schimke.composeai.uibuilder.protocol.WindowPostureV1
import ee.schimke.composeai.uibuilder.service.AuthenticatedUiBuilderActor
import ee.schimke.composeai.uibuilder.service.RevisionPinnedUiBuilderExport
import ee.schimke.composeai.uibuilder.toDesignDocumentV1
import ee.schimke.composeai.uibuilder.wearScreenUiBuilderDocument
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.encodeToJsonElement

/**
 * The export action for the designs that have no component record and never will.
 *
 * `remote-m3` and `wear-m3` are not catalogs someone forgot to run discovery against: a Wear widget
 * ships as Remote Compose inside a `WearWidgetDocument` and a Wear screen's `ScreenScaffold` takes
 * a scroll state no recovered signature describes, so both are written by their own emitters. Until
 * this, only the editor's Code pane called them — the server's export reported `remote-m3` as
 * non-exportable, and the one artifact a designer could not get out of the builder was the one it
 * had just generated for them on screen.
 *
 * Asserted through the executor with a **deliberately unconfigured** record source, because that is
 * the deployment: the packaged image runs `--ui-builder-catalogs m3-catalog,remote-m3` and passes a
 * record for the first only. An export that needed one here would be an export nobody receives.
 */
class RecordFreeComposeExportTest {

  private val executor =
    ScreenGeneratorComposeExportExecutor(
      { ComponentRecordSource.Lookup.Unconfigured },
      PACKAGE_NAME,
    )

  @Test
  fun `a wear widget design exports as a file, with a package and no diagnostic`() {
    val artifact = export(widget())

    assertEquals(emptyList(), artifact.diagnostics)
    assertEquals(ExportFormatV1.COMPOSE, artifact.format)
    assertEquals("text/x-kotlin; charset=utf-8", artifact.mediaType)
    assertEquals(ExportEncodingV1.UTF8, artifact.encoding)
    // Provenance first, then the file annotation Kotlin requires before the package, then the
    // package the Code pane's snippet deliberately does not carry.
    assertTrue(
      artifact.content.startsWith("// Generated by compose-preview serve"),
      artifact.content,
    )
    assertTrue(
      "@file:Suppress(\"RestrictedApi\")\n\npackage $PACKAGE_NAME\n" in artifact.content,
      artifact.content,
    )
    // It is the widget's own source, not a Material 3 screen's.
    assertTrue("class HelloWidget : GlanceWearWidget()" in artifact.content, artifact.content)
    assertTrue("@RemoteComposable" in artifact.content, artifact.content)
    // The scaffold is erased, exactly as the Code pane erases it. `remote-m3/widget-container-*` is
    // this builder's stand-in for `WearWidgetContainer`, and on-device that frame belongs to the
    // launcher: it draws it around content from `WearWidgetParams`. An export that named it would
    // hand somebody a file drawing a second frame inside the host's.
    assertFalse("widget-container" in artifact.content, artifact.content)
    assertFalse("WearWidgetContainer" in artifact.content, artifact.content)
    // What the container's background becomes instead: the widget's own brush, which is what the
    // host paints the squircle with.
    assertTrue(
      "WearWidgetDocument(background = WearWidgetBrush.color(colorScheme.primary))" in
        artifact.content,
      artifact.content,
    )
    // And its size picks the preview params provider rather than being emitted as a dimension.
    assertTrue("SquircleSmallWidgetPreviewParams::class" in artifact.content, artifact.content)
    // The provenance names the revision and catalog the artifact was pinned to, as the
    // record-driven
    // export does; a file on somebody's disk is traceable either way.
    assertTrue("Design widget-1 revision 0" in artifact.content, artifact.content)
    assertTrue("Catalog remote-m3@candidate" in artifact.content, artifact.content)
  }

  @Test
  fun `a wear screen design exports the same way`() {
    val artifact = export(wearScreen())

    assertEquals(emptyList(), artifact.diagnostics)
    assertTrue("package $PACKAGE_NAME\n" in artifact.content, artifact.content)
    assertTrue("@WearPreviewDevices" in artifact.content, artifact.content)
  }

  @Test
  fun `the same design refuses only as a native preview, and says why`() {
    // The export lane serves it; the compile lane cannot, and the reason it gives is the design's
    // language rather than a missing record an operator would go and configure for nothing.
    val refused =
      executor.generate(widget()) as ScreenGeneratorComposeExportExecutor.Generated.Refused

    assertEquals(ScreenGeneratorComposeExportExecutor.RECORD_FREE_DESIGN, refused.code)
    assertTrue(refused.reasons.single().contains("Remote Compose"), refused.reasons.toString())
  }

  @Test
  fun `a design the emitter cannot write refuses as the document's own fault`() {
    // Padding the *container* owns, and a widget cannot choose: the shipped preview params carry
    // 8dp, so no generated preview could show 20dp. The emitter refuses by name rather than
    // emitting a widget whose preview draws a frame the design does not have — the same judgement
    // the Code pane makes, now reaching the export.
    val artifact = export(widget(horizontalPaddingDp = 20.0))

    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.UNEXPRESSIBLE_DOCUMENT),
      artifact.diagnostics.map { it.code },
    )
    assertTrue("horizontal padding is 20dp" in artifact.diagnostics.single().message)
  }

  @Test
  fun `an ordinary screen is left to the record-driven generator`() {
    assertNull(RecordFreeExport.generate(ScreenGeneratorScreenFixture.document()))
    // And the executor still refuses it for the reason it always did, rather than for this one.
    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.NO_COMPONENT_RECORD),
      export(ScreenGeneratorScreenFixture.document()).diagnostics.map { it.code },
    )
  }

  @Test
  fun `the record-free catalogs are the two that ship without a record`() {
    assertEquals(setOf("remote-m3", "wear-m3"), RecordFreeExport.CATALOG_SYSTEM_IDS)
  }

  private fun export(document: DesignDocumentV1) =
    executor.export(
      RevisionPinnedUiBuilderExport(
        actor = AuthenticatedUiBuilderActor("tester"),
        designId = document.id,
        revision = document.revision,
        documentHash = "hash",
        document = document,
        catalog = catalog,
        format = ExportFormatV1.COMPOSE,
      )
    )

  /** The Hello sample, optionally with a padding the widget host does not let a design choose. */
  private fun widget(horizontalPaddingDp: Double? = null): DesignDocumentV1 {
    val document =
      helloWidgetUiBuilderDocument("widget-1", pin("remote-m3"), environment).let { design ->
        if (horizontalPaddingDp == null) return@let design
        val rootId = design.roots.single()
        val root = design.nodes.getValue(rootId)
        design.copy(
          nodes =
            design.nodes +
              (rootId to
                root.copy(
                  properties =
                    JsonObject(
                      root.properties +
                        ("horizontalPaddingDp" to
                          json.parseToJsonElement(
                            """{"type":"float","value":$horizontalPaddingDp}"""
                          ))
                    )
                ))
        )
      }
    return document.toDesignDocumentV1()
  }

  private fun wearScreen(): DesignDocumentV1 =
    wearScreenUiBuilderDocument("screen-1", pin("wear-m3"), environment).toDesignDocumentV1()

  private fun pin(systemId: String): JsonObject =
    json
      .encodeToJsonElement(
        CatalogReferenceV1(
          systemId = systemId,
          catalogRevision = "candidate",
          capabilityDigest = "candidate",
          nativeRuntimeId = "candidate",
        )
      )
      .let { it as JsonObject }

  private val environment: JsonObject =
    json
      .encodeToJsonElement(
        DesignEnvironmentV1(
          widthDp = 216,
          heightDp = 76,
          density = 1.0,
          theme = ThemeV1.DARK,
          locale = "en-US",
          fontScale = 1.0,
          layoutDirection = LayoutDirectionV1.LTR,
          windowPosture = WindowPostureV1.FLAT,
          animations = AnimationStateV1.SETTLED,
          networkAccess = false,
        )
      )
      .let { it as JsonObject }

  private val catalog =
    CatalogCapabilityV1(
      schema = "compose-catalog-capabilities/v1",
      benchmark = CatalogBenchmarkV1("test", "source", "remote-m3", "candidate", "candidate"),
      components = emptyList(),
      exportCapabilities = ExportCapabilitiesV1(composeCode = true, svg = false, png = false),
    )

  private companion object {
    const val PACKAGE_NAME = "generated.uibuilder"

    val json = Json {
      classDiscriminator = "type"
      encodeDefaults = true
      explicitNulls = false
      ignoreUnknownKeys = true
    }
  }
}
