package ee.schimke.composeai.cli.serve

import ee.schimke.composeai.discovery.ComponentRecord
import ee.schimke.composeai.discovery.ComponentRecordFile
import ee.schimke.composeai.uibuilder.RecordFreeExport
import ee.schimke.composeai.uibuilder.helloWidgetUiBuilderDocument
import ee.schimke.composeai.uibuilder.protocol.AnimationStateV1
import ee.schimke.composeai.uibuilder.protocol.CatalogBenchmarkV1
import ee.schimke.composeai.uibuilder.protocol.CatalogCapabilityV1
import ee.schimke.composeai.uibuilder.protocol.CatalogReferenceV1
import ee.schimke.composeai.uibuilder.protocol.DesignDocumentV1
import ee.schimke.composeai.uibuilder.protocol.DesignEnvironmentV1
import ee.schimke.composeai.uibuilder.protocol.ExportCapabilitiesV1
import ee.schimke.composeai.uibuilder.protocol.ExportEncodingV1
import ee.schimke.composeai.uibuilder.protocol.ExportFormatV1
import ee.schimke.composeai.uibuilder.protocol.LayoutDirectionV1
import ee.schimke.composeai.uibuilder.protocol.ThemeV1
import ee.schimke.composeai.uibuilder.protocol.WindowPostureV1
import ee.schimke.composeai.uibuilder.service.AuthenticatedUiBuilderActor
import ee.schimke.composeai.uibuilder.service.RevisionPinnedUiBuilderExport
import ee.schimke.composeai.uibuilder.toDesignDocumentV1
import ee.schimke.composeai.uibuilder.wearScreenUiBuilderDocument
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.encodeToJsonElement

/**
 * The export action for the designs that have no component record and never will.
 *
 * `remote-m3` and `wear-m3` are not catalogs someone forgot to run discovery against: a Wear widget
 * ships as Remote Compose inside a `WearWidgetDocument` and a Wear screen's `ScreenScaffold` takes
 * a scroll state no recovered signature describes, so both are written by their own emitters. Until
 * this, only the editor's Code pane called them — the server's export reported `remote-m3` as
 * non-exportable, and the one artifact a designer could not get out of the builder was the one it
 * had just generated for them on screen.
 *
 * Asserted through the executor with a **deliberately unconfigured** record source, because that is
 * the deployment: the packaged image runs `--ui-builder-catalogs m3-catalog,remote-m3` and passes a
 * record for the first only. An export that needed one here would be an export nobody receives.
 */
class RecordFreeComposeExportTest {

  private val executor =
    ScreenGeneratorComposeExportExecutor(
      { ComponentRecordSource.Lookup.Unconfigured },
      PACKAGE_NAME,
    )

  @Test
  fun `a wear widget design exports as a file, with a package and no diagnostic`() {
    val artifact = export(widget())

    assertEquals(emptyList(), artifact.diagnostics)
    assertEquals(ExportFormatV1.COMPOSE, artifact.format)
    assertEquals("text/x-kotlin; charset=utf-8", artifact.mediaType)
    assertEquals(ExportEncodingV1.UTF8, artifact.encoding)
    // Provenance first, then the file annotation Kotlin requires before the package, then the
    // package the Code pane's snippet deliberately does not carry.
    assertTrue(
      artifact.content.startsWith("// Generated by compose-preview serve"),
      artifact.content,
    )
    assertTrue(
      "@file:Suppress(\"RestrictedApi\")\n\npackage $PACKAGE_NAME\n" in artifact.content,
      artifact.content,
    )
    // It is the widget's own source, not a Material 3 screen's.
    assertTrue("class HelloWidget : GlanceWearWidget()" in artifact.content, artifact.content)
    assertTrue("@RemoteComposable" in artifact.content, artifact.content)
    // The scaffold is erased, exactly as the Code pane erases it. `remote-m3/widget-container-*` is
    // this builder's stand-in for `WearWidgetContainer`, and on-device that frame belongs to the
    // launcher: it draws it around content from `WearWidgetParams`. An export that named it would
    // hand somebody a file drawing a second frame inside the host's.
    assertFalse("widget-container" in artifact.content, artifact.content)
    assertFalse("WearWidgetContainer" in artifact.content, artifact.content)
    // What the container's background becomes instead: the widget's own brush, which is what the
    // host paints the squircle with.
    assertTrue(
      "WearWidgetDocument(background = WearWidgetBrush.color(colorScheme.primary))" in
        artifact.content,
      artifact.content,
    )
    // And its size picks the preview params providers rather than being emitted as a dimension —
    // one footprint from each rather than a preview unrolled per value. Two shapes, because the
    // rectangular render is the one recommended as the widget picker editor's image and a designer
    // should not have to hand-write a `@Preview` to see it.
    assertTrue(
      "SquircleSmallWidgetPreviewParams().values.maxBy { it.widthDp }" in artifact.content,
      artifact.content,
    )
    assertTrue(
      "RectangularSmallWidgetPreviewParams().values.maxBy { it.widthDp }" in artifact.content,
      artifact.content,
    )
    // The provenance names the revision and catalog the artifact was pinned to, as the
    // record-driven
    // export does; a file on somebody's disk is traceable either way.
    assertTrue("Design widget-1 revision 0" in artifact.content, artifact.content)
    assertTrue("Catalog remote-m3@candidate" in artifact.content, artifact.content)
  }

  @Test
  fun `a wear screen design exports the same way`() {
    val artifact = export(wearScreen())

    assertEquals(emptyList(), artifact.diagnostics)
    assertTrue("package $PACKAGE_NAME\n" in artifact.content, artifact.content)
    assertTrue("@WearPreviewDevices" in artifact.content, artifact.content)
  }

  @Test
  fun `the same design generates different source for the native preview lane`() {
    // Two files for two readers, from one design. The export above is what a designer pastes into
    // their own module — a widget class, a provider-driven preview — and this is what the host
    // compiles to draw the thing: the body, the brush and the container spec, with no
    // `GlanceWearWidget` in it for anything to construct.
    val generated =
      executor.generate(widget()) as ScreenGeneratorComposeExportExecutor.Generated.Emitted

    assertEquals("HelloWidget", generated.screenName)
    assertTrue("fun HelloWidgetContent() {" in generated.source, generated.source)
    assertTrue(
      "fun HelloWidgetBackground(): WearWidgetBrush {" in generated.source,
      generated.source,
    )
    assertTrue("fun HelloWidgetParams(): WearWidgetParams =" in generated.source, generated.source)
    assertFalse("GlanceWearWidget" in generated.source, generated.source)
    assertFalse("WearWidgetPreviewParams" in generated.source, generated.source)
    // The Small container's own frame — 200×60dp of content inside 8dp of host padding — rather
    // than the design environment, which describes a watch screen.
    assertEquals(
      ScreenGeneratorComposeExportExecutor.Generated.WidgetFrame(216, 76),
      generated.widgetFrame,
    )
  }

  @Test
  fun `a widget the export refuses for its padding still renders natively`() {
    // The export's refusal is true of a *pasteable file*: only the shipped providers can be named
    // in one, and they carry 8dp. This host constructs the params itself, so the design gets the
    // padding it authored and a picture of it.
    val artifact = export(widget(horizontalPaddingDp = 20.0))
    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.UNEXPRESSIBLE_DOCUMENT),
      artifact.diagnostics.map { it.code },
    )

    val generated =
      executor.generate(widget(horizontalPaddingDp = 20.0))
        as ScreenGeneratorComposeExportExecutor.Generated.Emitted

    assertTrue("horizontalPaddingDp = 20f" in generated.source, generated.source)
    // 200dp of content between 20dp of padding on each edge.
    assertEquals(
      ScreenGeneratorComposeExportExecutor.Generated.WidgetFrame(240, 76),
      generated.widgetFrame,
    )
  }

  @Test
  fun `a design the emitter cannot write refuses as the document's own fault`() {
    // Padding the *container* owns, and a widget cannot choose: the shipped preview params carry
    // 8dp, so no generated preview could show 20dp. The emitter refuses by name rather than
    // emitting a widget whose preview draws a frame the design does not have — the same judgement
    // the Code pane makes, now reaching the export.
    val artifact = export(widget(horizontalPaddingDp = 20.0))

    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.UNEXPRESSIBLE_DOCUMENT),
      artifact.diagnostics.map { it.code },
    )
    assertTrue("horizontal padding is 20dp" in artifact.diagnostics.single().message)
  }

  @Test
  fun `an ordinary screen is left to the record-driven generator`() {
    assertNull(RecordFreeExport.generate(ScreenGeneratorScreenFixture.document()))
    // And the executor still refuses it for the reason it always did, rather than for this one.
    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.NO_COMPONENT_RECORD),
      export(ScreenGeneratorScreenFixture.document()).diagnostics.map { it.code },
    )
  }

  @Test
  fun `an arbitrary Remote catalog exports ordinary roots using its declared platform`() {
    val original =
      json.decodeFromString<DesignDocumentV1>(
        java.io
          .File("../docs/design/evidence/ui-builder-live-document-preview/sample.document.json")
          .readText()
      )
    val document = original.copy(catalogPin = original.catalogPin.copy(systemId = "custom-remote"))
    val capabilities =
      catalog.copy(
        statusSemantics = JsonObject(mapOf("platform" to JsonPrimitive("remote-compose")))
      )
    val artifact = export(document, capabilities)
    assertTrue(artifact.diagnostics.isEmpty(), artifact.diagnostics.toString())
    assertTrue("RemoteStateLayout" in artifact.content, artifact.content)
    assertTrue(".clickable(valueChange(page, 20.ri))" in artifact.content, artifact.content)
    assertFalse("WearWidget" in artifact.content, artifact.content)
  }

  /**
   * The record fallback, through the executor a server actually builds.
   *
   * `RemoteContentEmitter` falls back to the component record for a component it has no
   * hand-written case for, and that fallback shipped unreachable: the only component map this
   * executor could build was a **pack**'s, and `remote-m3` is not a pack of itself, so an ordinary
   * widget holding an ordinary catalog component still refused. Unit tests passed the map directly
   * and could not see it.
   *
   * So this asks the production question — build the executor the way `ServeRunner` builds it and
   * export a design — and asks it BOTH ways, because only the pair is evidence. Without the publish
   * the component refuses by name, which is the honest answer for a host that composed no catalog;
   * with it the same design writes the call.
   *
   * `remote-m3/remote-text` is the subject because it is the plainest thing a Remote design is made
   * of and the emitter has no case for it: one required parameter, a `RemoteString`.
   */
  @Test
  fun `a published catalog's own component exports, and refuses without the publish`() {
    val design = widgetAroundRemoteText()

    val unpublished = export(design)
    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.UNEXPRESSIBLE_DOCUMENT),
      unpublished.diagnostics.map { it.code },
      unpublished.content,
    )
    assertTrue("remote-m3/remote-text" in unpublished.diagnostics.single().message)

    val artifact =
      publishedExecutor.export(
        RevisionPinnedUiBuilderExport(
          actor = AuthenticatedUiBuilderActor("tester"),
          designId = design.id,
          revision = design.revision,
          documentHash = "hash",
          document = design,
          catalog = catalog,
          format = ExportFormatV1.COMPOSE,
        )
      )

    assertEquals(emptyList(), artifact.diagnostics, artifact.content)
    assertTrue("RemoteText(" in artifact.content, artifact.content)
    assertTrue("text = \"Hello\".rs" in artifact.content, artifact.content)

    // And the picture, which is a third lane rather than the same one: the native preview
    // exporter builds its own emitter. A design whose file writes a component and whose render
    // refuses it is a hole in the canvas nobody can explain from the artifact.
    val preview =
      publishedExecutor.generate(design) as ScreenGeneratorComposeExportExecutor.Generated.Emitted
    assertTrue("RemoteText(" in preview.source, preview.source)
    assertTrue(
      executor.generate(design) is ScreenGeneratorComposeExportExecutor.Generated.Refused,
      "the same design must refuse for the host that composed no catalog",
    )
  }

  /**
   * A published catalog's components are version-checked, like every other record this executor
   * reads.
   *
   * `ComponentRecordSource` deserialises a newer schema with unknown fields ignored — deliberately,
   * so a host serving a catalog built by a newer plugin still shows a shelf. Generating from one is
   * a different question, and the record-driven lane and the pack lane both refuse it by version.
   * The published half went straight to the emitter, which would write Kotlin from a shape nobody
   * promised where the other two say which version they read and what to re-run. Raised in review
   * on #691.
   */
  @Test
  fun `a published catalog on a schema this build will not generate from refuses by version`() {
    val ahead =
      ScreenGeneratorComposeExportExecutor(
        { ComponentRecordSource.Lookup.Found(remoteM3Record.copy(schemaVersion = 99)) },
        PACKAGE_NAME,
        publishedComponents = { publishedRemoteM3 },
      )

    val artifact =
      ahead.export(
        RevisionPinnedUiBuilderExport(
          actor = AuthenticatedUiBuilderActor("tester"),
          designId = widgetAroundRemoteText().id,
          revision = widgetAroundRemoteText().revision,
          documentHash = "hash",
          document = widgetAroundRemoteText(),
          catalog = catalog,
          format = ExportFormatV1.COMPOSE,
        )
      )

    assertEquals(
      listOf(ScreenGeneratorComposeExportExecutor.NO_COMPONENT_RECORD),
      artifact.diagnostics.map { it.code },
      artifact.content,
    )
    assertTrue("is schema 99" in artifact.diagnostics.single().message)
  }

  @Test
  fun `the record-free catalogs are the two that ship without a record`() {
    assertEquals(setOf("remote-m3", "wear-m3"), RecordFreeExport.CATALOG_SYSTEM_IDS)
  }

  /**
   * What `remote-m3` composes to on a host that reads its published file — the map `ServeRunner`
   * hands the executor, built here by the same call it makes.
   */
  private val remoteM3Record: ComponentRecordFile by lazy {
    json.decodeFromString(
      java.io.File("../docs/design/fixtures/ui-builder/remote-m3-record-v1.json").readText()
    )
  }

  private val publishedRemoteM3: Map<String, ComponentRecord> by lazy {
    val fixtures = java.io.File("../docs/design/fixtures/ui-builder")
    val record = remoteM3Record
    val composed =
      PublishedUiBuilderCatalog.compose(
        fixtures.resolve("remote-m3-published-v1.json").readText(),
        record,
        ExportCapabilitiesV1(composeCode = true, svg = false, png = false),
      )
    assertTrue(composed is PublishedUiBuilderCatalog.Result.Composed, composed.toString())
    (composed as PublishedUiBuilderCatalog.Result.Composed).records
  }

  /** The executor as a host serving the published `remote-m3` catalog builds it. */
  private val publishedExecutor by lazy {
    ScreenGeneratorComposeExportExecutor(
      { ComponentRecordSource.Lookup.Unconfigured },
      PACKAGE_NAME,
      publishedComponents = { systemId ->
        if (systemId == "remote-m3") publishedRemoteM3 else emptyMap()
      },
    )
  }

  /** The Hello widget with its text swapped for the catalog's own `RemoteText`. */
  private fun widgetAroundRemoteText(): DesignDocumentV1 {
    val document = helloWidgetUiBuilderDocument("widget-1", pin("remote-m3"), environment)
    val text = document.nodes.getValue("hello-text")
    return document
      .copy(
        nodes =
          document.nodes +
            ("hello-text" to
              text.copy(
                componentId = "remote-m3/remote-text",
                properties =
                  JsonObject(
                    mapOf(
                      "text" to json.parseToJsonElement("""{"type":"string","value":"Hello"}""")
                    )
                  ),
              ))
      )
      .toDesignDocumentV1()
  }

  private fun export(document: DesignDocumentV1, capabilities: CatalogCapabilityV1 = catalog) =
    executor.export(
      RevisionPinnedUiBuilderExport(
        actor = AuthenticatedUiBuilderActor("tester"),
        designId = document.id,
        revision = document.revision,
        documentHash = "hash",
        document = document,
        catalog = capabilities,
        format = ExportFormatV1.COMPOSE,
      )
    )

  /** The Hello sample, optionally with a padding the widget host does not let a design choose. */
  private fun widget(horizontalPaddingDp: Double? = null): DesignDocumentV1 {
    val document =
      helloWidgetUiBuilderDocument("widget-1", pin("remote-m3"), environment).let { design ->
        if (horizontalPaddingDp == null) return@let design
        val rootId = design.roots.single()
        val root = design.nodes.getValue(rootId)
        design.copy(
          nodes =
            design.nodes +
              (rootId to
                root.copy(
                  properties =
                    JsonObject(
                      root.properties +
                        ("horizontalPaddingDp" to
                          json.parseToJsonElement(
                            """{"type":"float","value":$horizontalPaddingDp}"""
                          ))
                    )
                ))
        )
      }
    return document.toDesignDocumentV1()
  }

  private fun wearScreen(): DesignDocumentV1 =
    wearScreenUiBuilderDocument("screen-1", pin("wear-m3"), environment).toDesignDocumentV1()

  private fun pin(systemId: String): JsonObject =
    json
      .encodeToJsonElement(
        CatalogReferenceV1(
          systemId = systemId,
          catalogRevision = "candidate",
          capabilityDigest = "candidate",
          nativeRuntimeId = "candidate",
        )
      )
      .let { it as JsonObject }

  private val environment: JsonObject =
    json
      .encodeToJsonElement(
        DesignEnvironmentV1(
          widthDp = 216,
          heightDp = 76,
          density = 1.0,
          theme = ThemeV1.DARK,
          locale = "en-US",
          fontScale = 1.0,
          layoutDirection = LayoutDirectionV1.LTR,
          windowPosture = WindowPostureV1.FLAT,
          animations = AnimationStateV1.SETTLED,
          networkAccess = false,
        )
      )
      .let { it as JsonObject }

  private val catalog =
    CatalogCapabilityV1(
      schema = "compose-catalog-capabilities/v1",
      benchmark = CatalogBenchmarkV1("test", "source", "remote-m3", "candidate", "candidate"),
      components = emptyList(),
      exportCapabilities = ExportCapabilitiesV1(composeCode = true, svg = false, png = false),
    )

  private companion object {
    const val PACKAGE_NAME = "generated.uibuilder"

    val json = Json {
      classDiscriminator = "type"
      encodeDefaults = true
      explicitNulls = false
      ignoreUnknownKeys = true
    }
  }
}
