package ee.schimke.composeai.cli.serve

import ee.schimke.composeai.uibuilder.export.ScreenExportGate
import ee.schimke.composeai.uibuilder.export.TypefaceTarget
import ee.schimke.composeai.uibuilder.export.UiBuilderBuildFeatures
import ee.schimke.composeai.uibuilder.protocol.CatalogBenchmarkV1
import ee.schimke.composeai.uibuilder.protocol.CatalogCapabilityV1
import ee.schimke.composeai.uibuilder.protocol.ColorValueV1
import ee.schimke.composeai.uibuilder.protocol.ComposeSourceExportCapabilityV1
import ee.schimke.composeai.uibuilder.protocol.DesignDocumentV1
import ee.schimke.composeai.uibuilder.protocol.DesignNodeV1
import ee.schimke.composeai.uibuilder.protocol.DiagnosticSeverityV1
import ee.schimke.composeai.uibuilder.protocol.ExportCapabilitiesV1
import ee.schimke.composeai.uibuilder.protocol.ExportEncodingV1
import ee.schimke.composeai.uibuilder.protocol.ExportFormatV1
import ee.schimke.composeai.uibuilder.protocol.StateValueV1
import ee.schimke.composeai.uibuilder.protocol.StringValueV1
import ee.schimke.composeai.uibuilder.protocol.ThemeV1
import ee.schimke.composeai.uibuilder.service.AuthenticatedUiBuilderActor
import ee.schimke.composeai.uibuilder.service.RevisionPinnedUiBuilderExport
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertTrue
import kotlinx.serialization.json.Json

/**
 * The export a served host returns, asserted as a golden because the claim is that the output is
 * exact and complete. The golden was compiled against material3/foundation/ui once; a standing CI
 * compile gate is a follow-up. Changes to the pinned `preview-discovery` (e.g. import resolution in
 * receiver-scoped slots) or to `ScreenDocumentProjection` (the card content `Box`) surface here as
 * a red golden.
 */
class ScreenGeneratorComposeExportExecutorTest {

  @Test
  fun `semantic loops and reusable components have identical browser and service source`() {
    val root =
      generateSequence(File(".").absoluteFile) { it.parentFile }
        .first { File(it, "docs/design/fixtures/ui-builder/m3-catalog-components-v1.json").isFile }
    val document =
      Json.decodeFromString<DesignDocumentV1>(
        File(
            root,
            "docs/design/evidence/ui-builder-repetition-export/repetition-initial.document.json",
          )
          .readText()
      )
    val record = ExportRecords.m3Catalog()
    val browser = ScreenExportGate.export(document, record)
    val scopedGeneratorAvailable = runCatching {
      Json.decodeFromString<ee.schimke.composeai.discovery.ScreenDocument>(
        """{"name":"Probe","functions":[],"root":{"componentId":"","repetition":{"fields":{},"rows":[]}}}"""
      )
    }
      .isSuccess
    if (!scopedGeneratorAvailable) {
      assertTrue(
        browser is ScreenExportGate.Outcome.Refused &&
          browser.reasons.any { "shared generator support" in it }
      )
      return
    }
    // A second gate below the vocabulary: `ScreenDocumentProjection` refuses repetitions, component
    // instances, event bindings and state-bound properties unless
    // `UiBuilderBuildFeatures.remoteCompose` is set. The probe above answers "can the vocabulary
    // say this?", not "will this build emit it?". Asserted rather than skipped: with the feature
    // off both halves must still refuse for the same reason, which catches a build that drops one
    // gate but keeps the other.
    if (!UiBuilderBuildFeatures.remoteCompose) {
      assertTrue(
        browser is ScreenExportGate.Outcome.Refused &&
          browser.reasons.any { "disabled in this build" in it }
      )
      return
    }
    val artifact =
      ScreenGeneratorComposeExportExecutor(
          { ComponentRecordSource.Lookup.Found(record) },
          ScreenExportGate.PACKAGE_NAME,
        )
        .export(
          RevisionPinnedUiBuilderExport(
            actor = AuthenticatedUiBuilderActor("tester"),
            designId = document.id,
            revision = document.revision,
            documentHash = "hash",
            document = document,
            catalog = catalog,
            format = ExportFormatV1.COMPOSE,
          )
        )
    assertEquals(emptyList(), artifact.diagnostics)
    val provenance =
      "// Generated by compose-preview serve from a UI-builder design.\n" +
        "// Design ${document.id} revision ${document.revision}\n" +
        "// Document SHA-256: hash\n" +
        "// Catalog ${document.catalogPin.systemId}@${document.catalogPin.catalogRevision}; capability ${document.catalogPin.capabilityDigest}\n\n"
    assertEquals(
      provenance + (browser as ScreenExportGate.Outcome.Emitted).source,
      artifact.content,
    )
    assertTrue(artifact.content.orEmpty().contains(".forEach"))
    assertTrue(artifact.content.orEmpty().contains("private fun Pair("))
  }

  private val catalog =
    CatalogCapabilityV1.Builder(
        "compose-catalog-capabilities/v1",
        CatalogBenchmarkV1.Builder("test", "source", "test-catalog", "candidate", "candidate")
          .build(),
        emptyList(),
      )
      .also {
        it.exportCapabilities =
          ExportCapabilitiesV1.Builder()
            .also {
              it.composeCode = true
              it.svg = false
              it.png = false
            }
            .build()
      }
      .build()

  private fun export(
    document: DesignDocumentV1 = ScreenGeneratorScreenFixture.document(),
    catalog: CatalogCapabilityV1 = this.catalog,
    components: (String) -> ComponentRecordSource.Lookup = {
      ComponentRecordSource.Lookup.Found(ScreenGeneratorScreenFixture.components())
    },
  ) =
    ScreenGeneratorComposeExportExecutor(components, ScreenGeneratorScreenFixture.PACKAGE_NAME)
      .export(
        RevisionPinnedUiBuilderExport(
          actor = AuthenticatedUiBuilderActor("tester"),
          designId = document.id,
          revision = document.revision,
          documentHash = "hash",
          document = document,
          catalog = catalog,
          format = ExportFormatV1.COMPOSE,
        )
      )

  @Test
  fun `a design document exports as the complete screen, with no diagnostic at all`() {
    val artifact = export()
    assertEquals(EXPECTED_SOURCE, artifact.content)
    assertEquals(emptyList(), artifact.diagnostics)
    assertEquals(ExportFormatV1.COMPOSE, artifact.format)
    assertEquals("text/x-kotlin; charset=utf-8", artifact.mediaType)
    assertEquals(ExportEncodingV1.UTF8, artifact.encoding)
  }

  @Test
  fun `an unknown catalog source adapter refuses rather than falling back`() {
    val unknownCatalog =
      catalog
        .newBuilder()
        .also {
          it.composeSourceExport =
            ComposeSourceExportCapabilityV1.Builder("other-compose", 7).build()
        }
        .build()

    val artifact = export(catalog = unknownCatalog)

    assertTrue(artifact.content.orEmpty().contains("other-compose/v7"))
    assertEquals(
      ScreenGeneratorComposeExportExecutor.UNSUPPORTED_SOURCE_ADAPTER,
      artifact.diagnostics.single().code,
    )
  }

  /**
   * A themed `m3/surface` exports wrapped in `MaterialTheme`; the projection's added
   * `MaterialTheme` record must reach this executor's generator call too.
   */
  @Test
  fun `a themed surface exports its theme, as the browser does`() {
    val document = themedDocument()
    val record = ExportRecords.m3Catalog()
    val browser = ScreenExportGate.export(document, record)
    val artifact =
      ScreenGeneratorComposeExportExecutor(
          { ComponentRecordSource.Lookup.Found(record) },
          ScreenExportGate.PACKAGE_NAME,
        )
        .export(
          RevisionPinnedUiBuilderExport(
            actor = AuthenticatedUiBuilderActor("tester"),
            designId = document.id,
            revision = document.revision,
            documentHash = "hash",
            document = document,
            catalog = catalog,
            format = ExportFormatV1.COMPOSE,
          )
        )
    assertEquals(emptyList(), artifact.diagnostics)
    val source = (browser as ScreenExportGate.Outcome.Emitted).source
    assertTrue(artifact.content.orEmpty().endsWith(source), artifact.content)
    assertTrue("MaterialTheme(colorScheme = colorScheme" in source, source)
    assertTrue("darkColorScheme(primary = Color(0xFFD0BCFF))" in source, source)
    assertTrue("GoogleFont(\"Michroma\")" in source, source)
  }

  /**
   * Lanes compiling against a Compose Desktop bundle ask for desktop typefaces (`GoogleFont` is
   * Android-only); this is the native preview's and `design render --local`'s generation.
   */
  @Test
  fun `a desktop lane writes a theme typeface as a system-font lookup and says so`() {
    val record = ExportRecords.m3Catalog()
    val executor =
      ScreenGeneratorComposeExportExecutor(
        { ComponentRecordSource.Lookup.Found(record) },
        ScreenExportGate.PACKAGE_NAME,
      )

    val desktop =
      assertIs<ScreenGeneratorComposeExportExecutor.Generated.Emitted>(
        executor.generate(themedDocument(), typefaces = TypefaceTarget.DESKTOP)
      )
    assertTrue("SystemFont(\"Michroma\"" in desktop.source, desktop.source)
    assertFalse("GoogleFont" in desktop.source, desktop.source)
    assertEquals(listOf("Michroma"), desktop.systemFontFamilies)

    val android =
      assertIs<ScreenGeneratorComposeExportExecutor.Generated.Emitted>(
        executor.generate(themedDocument())
      )
    assertTrue("GoogleFont(\"Michroma\")" in android.source, android.source)
    assertEquals(emptyList(), android.systemFontFamilies)
  }

  @Test
  fun `the same document exports byte-identically twice`() {
    assertEquals(export().contentDigest, export().contentDigest)
  }

  @Test
  fun `a host with no component record says so, rather than refusing every node`() {
    val artifact = export(components = { ComponentRecordSource.Lookup.Unconfigured })
    val diagnostic = artifact.diagnostics.single()
    assertEquals(DiagnosticSeverityV1.ERROR, diagnostic.severity)
    assertEquals(ScreenGeneratorComposeExportExecutor.NO_COMPONENT_RECORD, diagnostic.code)
    assertTrue(diagnostic.message.contains("catalog `test-catalog`"), diagnostic.message)
  }

  @Test
  fun `a configured record that will not load names the path, not the flag`() {
    // An operator who never passed `--ui-builder-components` must be told to; one who passed a
    // mistyped path needs the path.
    val artifact =
      export(components = { ComponentRecordSource.Lookup.Unusable("no readable file at `/nope`") })
    val message = artifact.diagnostics.single().message
    assertTrue(message.contains("/nope"), message)
    assertFalse(message.contains("--ui-builder-components"), message)
  }

  @Test
  fun `an unexpressible value is an error naming the node, not a warning about the file`() {
    val document = ScreenGeneratorScreenFixture.document()
    val artifact =
      export(
        document.copy(
          roots = listOf("text"),
          nodes =
            mapOf(
              "text" to
                DesignNodeV1(
                  id = "text",
                  componentId = "m3/text",
                  properties = mapOf("text" to StateValueV1("query")),
                )
            ),
        )
      )
    val diagnostic = artifact.diagnostics.single()
    assertEquals(DiagnosticSeverityV1.ERROR, diagnostic.severity)
    assertEquals(ScreenGeneratorComposeExportExecutor.UNEXPRESSIBLE_DOCUMENT, diagnostic.code)
    assertTrue(diagnostic.message.contains("state variable `query`"), diagnostic.message)
    // The refusal is also the content, so a caller that only renders the body sees the reason.
    assertTrue(artifact.content.startsWith("// node `text`.`text` reads"), artifact.content)
  }

  @Test
  fun `a record on an unreadable schema refuses per export, naming the version`() {
    // The version is checked per request, so a repaired file is seen on the next request.
    val artifact =
      export(
        components = {
          ComponentRecordSource.Lookup.Found(
            ScreenGeneratorScreenFixture.components()
              .newBuilder()
              .apply { schemaVersion = 99 }
              .build()
          )
        }
      )
    val diagnostic = artifact.diagnostics.single()
    assertEquals(ScreenGeneratorComposeExportExecutor.NO_COMPONENT_RECORD, diagnostic.code)
    assertTrue(diagnostic.message.contains("is schema 99"), diagnostic.message)
  }

  @Test
  fun `a node the catalog cannot place is a separate code from one it cannot express`() {
    val document = ScreenGeneratorScreenFixture.document()
    val artifact =
      export(
        document.copy(
          roots = listOf("text"),
          nodes =
            mapOf(
              "text" to
                DesignNodeV1(
                  id = "text",
                  componentId = "m3/marquee",
                  properties = mapOf("text" to StringValueV1("hi")),
                )
            ),
        )
      )
    val diagnostic = artifact.diagnostics.single()
    assertEquals(ScreenGeneratorComposeExportExecutor.UNPROVEN_CALL_SITE, diagnostic.code)
    assertEquals("no component `m3/marquee` in this catalog", diagnostic.message)
  }

  @Test
  fun `the default package is the one the preview adapter imports from`() {
    // Must match the package `UiBuilderGeneratedPreviewAdapter` imports; the golden passes one
    // explicitly and would not catch a different default.
    val document = ScreenGeneratorScreenFixture.document()
    val artifact =
      ScreenGeneratorComposeExportExecutor({
          ComponentRecordSource.Lookup.Found(ScreenGeneratorScreenFixture.components())
        })
        .export(
          RevisionPinnedUiBuilderExport(
            actor = AuthenticatedUiBuilderActor("tester"),
            designId = document.id,
            revision = document.revision,
            documentHash = "hash",
            document = document,
            catalog = catalog,
            format = ExportFormatV1.COMPOSE,
          )
        )
    assertTrue(artifact.content.contains("\npackage generated.uibuilder\n"), artifact.content)
    assertTrue(
      UiBuilderGeneratedPreviewAdapter.previewEntry("Screen", 1, 1)
        .contains("import generated.uibuilder.Screen")
    )
  }

  @Test
  fun `a refusal keeps every physical line commented, whatever the document put in it`() {
    // A refusal quotes document text, and a newline in it must not leave the rest uncommented.
    val document = ScreenGeneratorScreenFixture.document()
    val artifact =
      export(
        document.copy(
          roots = listOf("text"),
          nodes =
            mapOf(
              "text" to
                DesignNodeV1(
                  id = "text",
                  componentId = "m3/text",
                  properties =
                    mapOf(
                      "text" to StringValueV1("hi"),
                      "color" to ColorValueV1("bad\nval injected = 1\u2028val also = 2"),
                    ),
                )
            ),
        )
      )
    val lines = artifact.content.trimEnd('\n').split("\n")
    assertTrue(lines.size >= 3, artifact.content)
    assertTrue(lines.all { it.startsWith("// ") }, artifact.content)
  }

  private companion object {
    /**
     * Long lines, deliberately unformatted.
     *
     * The generator prints one call per line and does not wrap, because a formatter is a better
     * formatter than a code generator: ktfmt reads the whole file and knows where a break helps,
     * and a generator guessing at line breaks produces output a formatter then rewrites — two
     * layouts for one file, and a golden that drifts against whichever ran last.
     */
    val EXPECTED_SOURCE =
      """
// Generated by compose-preview serve from a UI-builder design.
// Design screen-generator-fixture revision 7
// Document SHA-256: hash
// Catalog test-catalog@candidate; capability fixture

package generated.uibuilder

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Card
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

@Composable
fun ScheduleOperations() {
    Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.surfaceContainer) {
        Column(modifier = Modifier.padding(start = 16.dp, top = 24.dp, end = 16.dp, bottom = 16.dp)) {
            Text(text = "Schedule", color = MaterialTheme.colorScheme.onBackground, style = MaterialTheme.typography.headlineSmall)
            Card(modifier = Modifier.fillMaxWidth().clip(MaterialTheme.shapes.medium), shape = MaterialTheme.shapes.medium) {
                Box(modifier = Modifier.fillMaxWidth()) {
                    Text(text = "Opening keynote", modifier = Modifier.width(120.dp), style = MaterialTheme.typography.bodyMedium)
                    Text(text = "09:00", color = Color(0xFF6750A4))
                }
            }
        }
    }
}
"""
        .trimStart('\n')
  }

  /**
   * A design that named devices gets one `@Preview(device = …)` per id, plus its own frame — the
   * size its author approved.
   */
  @Test
  fun `a named device set becomes one Preview each, beside the design's own frame`() {
    val base = ScreenGeneratorScreenFixture.document()
    val document =
      base.copy(
        environment =
          base.environment.copy(
            theme = ThemeV1.DARK,
            exportDevices = listOf("id:pixel_6", "id:pixel_fold"),
          )
      )

    val source = export(document).content

    assertTrue("""device = "id:pixel_6"""" in source, source)
    assertTrue("""device = "id:pixel_fold"""" in source, source)
    // The frame the design was drawn at, on its own wrapper.
    assertTrue("widthDp = 400," in source, source)
    assertTrue("heightDp = 800," in source, source)
    assertTrue("UI_MODE_NIGHT_YES" in source, source)
    // …and not on the device wrappers, which supply their own geometry.
    val fanOut = source.substringAfter("""device = "id:pixel_6"""")
    assertFalse("widthDp" in fanOut, fanOut)
  }

  /** A design that named none gets no `@Preview`, as the golden above pins. */
  @Test
  fun `a design naming no devices still carries no preview at all`() {
    val source = export().content

    assertFalse("@Preview" in source, source)
  }

  @Test
  fun `repeated refusals collapse into one line with a count`() {
    assertEquals(
      listOf("no component `m3/text` in this catalog (×3)", "`m3/icon` has no slot `x`"),
      ScreenGeneratorComposeExportExecutor.summarizeUnproven(
        listOf(
          "no component `m3/text` in this catalog",
          "`m3/icon` has no slot `x`",
          "no component `m3/text` in this catalog",
          "no component `m3/text` in this catalog",
        ),
        "m3-catalog",
        designComponentIds = setOf("m3/text", "m3/icon"),
        recordComponentIds = setOf("m3/icon"),
      ),
    )
  }

  @Test
  fun `a record that proves none of the design's components is named as the wrong file`() {
    val summary =
      ScreenGeneratorComposeExportExecutor.summarizeUnproven(
        listOf(
          "no component `m3/text` in this catalog",
          "no component `m3/icon` in this catalog",
          "no component `m3/text` in this catalog",
        ),
        "m3-catalog",
        designComponentIds = setOf("m3/text", "m3/icon", "layout/column"),
        recordComponentIds = setOf("Button/Filled", "Card/Outlined", "layout/column"),
      )

    assertTrue(
      summary.first().let {
        "proves none of this design's 2 components" in it &&
          "`Button/Filled`" in it &&
          "`m3/icon`" in it &&
          "discovery" in it
      },
      summary.first(),
    )
    assertEquals(
      listOf(
        "no component `m3/text` in this catalog (×2)",
        "no component `m3/icon` in this catalog",
      ),
      summary.drop(1),
    )
  }

  @Test
  fun `one missing component in an otherwise proven design is not blamed on the file`() {
    val reasons = listOf("no component `m3/navigation-suite-item` in this catalog")
    assertEquals(
      reasons,
      ScreenGeneratorComposeExportExecutor.summarizeUnproven(
        reasons,
        "m3-catalog",
        designComponentIds = setOf("m3/text", "m3/navigation-suite-item"),
        recordComponentIds = setOf("m3/text"),
      ),
    )
  }

  private fun themedDocument(): DesignDocumentV1 =
    Json.decodeFromString<DesignDocumentV1>(
      """
      {
        "schema": "compose-ui-builder-document/v1-candidate",
        "id": "themed", "title": "Themed", "revision": 0,
        "catalogPin": {"systemId": "m3-catalog", "catalogRevision": "candidate",
          "capabilityDigest": "candidate", "nativeRuntimeId": "candidate"},
        "environment": {"widthDp": 360, "heightDp": 640, "density": 1.0, "theme": "dark",
          "locale": "en-US", "fontScale": 1.0, "layoutDirection": "ltr"},
        "roots": ["screen"],
        "nodes": {
          "screen": {"id": "screen", "componentId": "m3/surface",
            "properties": {
              "themePrimaryColor": {"type": "string", "value": "#FFD0BCFF"},
              "themeDisplayTypeface": {"type": "string", "value": "Michroma"}
            },
            "slots": {"content": ["label"]}, "modifiers": []},
          "label": {"id": "label", "componentId": "m3/text",
            "properties": {"text": {"type": "string", "value": "Hello"},
              "color": {"type": "colorToken", "value": "primary"}},
            "slots": {}, "modifiers": []}
        }
      }
      """
    )
}
