// Bundles the serve web assets to IIFEs committed under the server's resources, where
// `ServeWebAssets` serves them. Committed so the Gradle release chain needs no Node; `npm run
// verify` (in CI) fails if the bundles drift from source.
//
// All entries stay classic scripts because Kotlin pages interleave synchronous inline bootstraps
// with them. `vue-runtime.js` publishes the `window.cpVue` façade synchronously so surface bundles
// don't each carry Vue.

import { build, context } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");

const assets = (name) =>
    resolve(
        root,
        "..",
        // Committed into the server module so Gradle remains Node-free.
        "server",
        "src",
        "main",
        "resources",
        "ee",
        "schimke",
        "composeai",
        "cli",
        "serve",
        "assets",
        name,
    );

// Bundles are split by where they load and what they cost:
// - `vue-runtime.js` precedes exactly one surface bundle, each carrying only that surface's
//   elements.
// - `serve-chrome.js` (URL state + Page theme) is on every page, Vue-free (~3 kB), and must run
//   before the component bundle and legacy scripts, which read `window.cpUrlState`.
// - `keyboard-navigation.js` is on every page but initializes after the full DOM exists.
// - `report-capture.js` is injected only when the report launcher opens or on `/report-bug`.
// - `format-compare.js` keeps its path and `window.ComposePreviewCompare` shape for its external
//   consumers (reference-score driver, compare audit).
// - `known-differences.js` is the acceptance engine (shared verbatim with
//   `scripts/design-artifacts/`), emitted only by the focused comparison.
// - `viewer.js` is viewer-only and the largest; it loads after `viewer-components.js` and
//   `format-compare.js`.
const BUNDLES = [
    { entry: "src/analytics.ts", out: "analytics.js" },
    { entry: "src/vueRuntime.ts", out: "vue-runtime.js" },
    { entry: "src/catalog.ts", out: "catalog-components.js" },
    { entry: "src/compare.ts", out: "compare-components.js" },
    { entry: "src/design.ts", out: "design-components.js" },
    { entry: "src/parity.ts", out: "parity-components.js" },
    { entry: "src/viewerComponents.ts", out: "viewer-components.js" },
    { entry: "src/remoteCompose.ts", out: "remote-compose.js" },
    { entry: "src/chrome.ts", out: "serve-chrome.js" },
    { entry: "src/keyboardNavigation.ts", out: "keyboard-navigation.js" },
    { entry: "src/reportCapture.ts", out: "report-capture.js" },
    { entry: "src/uidReference.ts", out: "uid-reference.js" },
    // Settings → Notifications. Its own bundle because it is emitted only beside a signed-in
    // session on a host with Web Push; `serve-chrome.js` is on every page, the front door included.
    { entry: "src/pushSettings.ts", out: "push-settings.js" },
    // The root-scoped push service worker. The server serves it at `/push-sw.js` (a worker's scope
    // is bounded by its path), not under `/assets/serve/`. Push and notificationclick only.
    { entry: "src/pushWorker.ts", out: "push-sw.js" },
    { entry: "src/formatCompare.ts", out: "format-compare.js" },
    // The comparison metric for a worker thread: a separate script loaded by URL, with no DOM.
    { entry: "src/scorer/scorerWorker.ts", out: "compare-scorer.js" },
    { entry: "src/knownDifferences.ts", out: "known-differences.js" },
    { entry: "src/viewer.ts", out: "viewer.js" },
    { entry: "src/spatial.ts", out: "spatial-view.js" },
];

const optionsFor = ({ entry, out }) => ({
    entryPoints: [resolve(root, entry)],
    outfile: assets(out),
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    // No sourcemap: it would be a second committed blob to keep in sync.
    sourcemap: false,
    logLevel: "info",
    legalComments: "none",
    minify: !watch,
    // Vue's compile-time feature flags, set so esbuild drops the Options API, prod devtools hooks
    // and hydration diagnostics this custom-element app never uses (and Vue's runtime warning).
    define: {
        __VUE_OPTIONS_API__: "false",
        __VUE_PROD_DEVTOOLS__: "false",
        __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
    },
    // Keep compiler settings identical between `tsc` and the emitted bundles.
    tsconfig: resolve(root, "tsconfig.json"),
    banner: {
        js: "/* Generated by serve-web — do not edit. Run `npm run build` in serve-web/. */",
    },
});

if (watch) {
    for (const bundle of BUNDLES) {
        const ctx = await context(optionsFor(bundle));
        await ctx.watch();
    }
    console.log("[esbuild] watching serve-web bundles…");
} else {
    for (const bundle of BUNDLES) await build(optionsFor(bundle));
}
