// The Model Context Protocol server (`compose-preview mcp serve`) as its own module. It lives here
// per `docs/design/REPOSITORY_LAYERS.md`: it runs a Ktor server for the UI-builder Streamable HTTP
// endpoint, which makes it layer 2. Its layer-1 dependencies (`daemon-core`, `render-session-api`,
// `daemon-client`, `render-matrix`) are published coordinates across the repository boundary.
//
// Sources keep the `ee.schimke.composeai.mcp` package (a rename is separate). It ships in the
// `compose-preview-mcp` distribution; the old `ee.schimke.composeai:mcp` coordinate stays at its
// last 1.x and no replacement Maven coordinate is published.
plugins {
  application
  alias(libs.plugins.kotlin.jvm)
  alias(libs.plugins.kotlin.serialization)
  alias(libs.plugins.ktfmt)
}

group = "ee.schimke.composeai"

// The artifact name (the Gradle project is `:mcp`); `compose-preview mcp serve` fetches
// `compose-preview-mcp-<version>.tar.gz`.
val publishedArtifactId = "compose-preview-mcp"

kotlin {
  jvmToolchain(libs.versions.java.server.get().toInt())
  sourceSets.named("main") {
    kotlin.srcDir(rootProject.tasks.named("generateMcpBuildFeatures"))
    resources.srcDir(rootProject.file("mcp-app"))
  }
}

ktfmt { googleStyle() }

// Same derivation as `:server` (`PLUGIN_VERSION` in CI, a patch-bumped SNAPSHOT from
// `.release-please-manifest.json` locally); ships in lockstep with the server.
version =
  providers.environmentVariable("PLUGIN_VERSION").orNull
    ?: run {
      val manifest = rootDir.resolve(".release-please-manifest.json").readText()
      val current = Regex(""""\.":\s*"([^"]+)"""").find(manifest)!!.groupValues[1]
      val (major, minor, patch) = current.split(".").map { it.toInt() }
      "$major.$minor.${patch + 1}-SNAPSHOT"
    }

base { archivesName.set(publishedArtifactId) }

application {
  applicationName = "compose-preview-mcp"
  mainClass.set("ee.schimke.composeai.mcp.DaemonMcpMain")
}

// The version reported in `initialize`'s `serverInfo.version`, generated into a resource read by
// `McpVersion.kt` (like `:server`'s `generateServeVersionResource`).
val generateMcpVersionResource =
  tasks.register("generateMcpVersionResource") {
    val outputDir = layout.buildDirectory.dir("generated/mcp-version-resource")
    val mcpVersion = project.version.toString()
    inputs.property("version", mcpVersion)
    outputs.dir(outputDir)
    doLast {
      val file = outputDir.get().file("ee/schimke/composeai/mcp/mcp-version.properties").asFile
      file.parentFile.mkdirs()
      file.writeText("version=$mcpVersion\n")
    }
  }

sourceSets.main.get().resources.srcDir(generateMcpVersionResource)

// The `.rc` viewer MCP App (`mcp-app/rc-viewer.html`) inlines the TypeScript Remote Compose player:
// the same bundle `:server` serves (`remote-compose-player-js-dist` plus
// `server/src/rc-player/inert-custom-host.js`), resolved here to avoid a project dependency for one
// file.
val rcPlayerJsDist =
  configurations.create("rcPlayerJsDist") {
    description = "The TypeScript Remote Compose player's browser bundle."
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
  }

dependencies {
  rcPlayerJsDist(
    variantOf(libs.remote.compose.player.js.dist) {
      classifier("dist")
      artifactType("zip")
    }
  )
}

val stageRcViewerPlayer =
  tasks.register<StageRcPlayerJs>("stageRcViewerPlayer") {
    archiveFile.set(
      layout.file(rcPlayerJsDist.elements.map { artifacts -> artifacts.single().asFile })
    )
    shimFile.set(
      rootProject.layout.projectDirectory.file("server/src/rc-player/inert-custom-host.js")
    )
    resourcePath.set("rc-viewer/rc-player-bundle.js")
    outputDirectory.set(layout.buildDirectory.dir("generated/rc-viewer-player"))
  }

sourceSets.main.get().resources.srcDir(stageRcViewerPlayer)

// `tar.gz` keeps the archive root as `compose-preview-mcp-<version>/`.
tasks.named<Tar>("distTar") {
  archiveExtension.set("tar.gz")
  compression = Compression.GZIP
}

// The same Java floor `:server`'s distribution carries (see its build file for why it's a file).
// Repeated rather than shared because each launcher looks beside the binary it resolved.
val writeDistributionJavaMin =
  tasks.register("writeDistributionJavaMin") {
    description = "Write the distribution's Java floor for a launcher to preflight."
    val manifest = layout.buildDirectory.file("generated/distribution/java-min.properties")
    val javaMin = libs.versions.java.server.get().toInt()
    inputs.property("javaMin", javaMin)
    outputs.file(manifest)
    doLast {
      manifest
        .get()
        .asFile
        .also { it.parentFile.mkdirs() }
        .writeText(
          buildString {
            appendLine("# Generated by :mcp:writeDistributionJavaMin. Do not edit.")
            appendLine("# The minimum Java feature version this distribution can run on.")
            appendLine("javaMin=$javaMin")
          }
        )
    }
  }

// The UI-builder editor archive, for `design_open`: its MCP App shell is
// `ui://compose-ui-builder/editor`, with assets served from a loopback origin
// (`UiBuilderAssetOrigin`). Resolved like `:server`'s (artifact-only from the release ivy repo, or
// `:ui-builder-web` under `-PcomposeUiBuilderDir`). Shipped as the ZIP and read in place (~12 MB vs
// ~45 MB unpacked) under a fixed name; the served version comes from the archive's manifest. An
// archive without `mcpApp` ships inert.
val uiBuilderWeb =
  configurations.create("uiBuilderWeb") {
    description = "Immutable Compose/Wasm UI-builder frontend archive, for design_open."
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
    attributes {
      attribute(Category.CATEGORY_ATTRIBUTE, objects.named("distribution"))
      attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named("ui-builder-web"))
      attribute(Usage.USAGE_ATTRIBUTE, objects.named("ui-builder-web"))
    }
  }

distributions {
  main {
    contents { from(writeDistributionJavaMin) }
    contents {
      from(uiBuilderWeb) {
        into("ui-builder")
        rename { "compose-preview-ui-builder-web.zip" }
      }
    }
  }
}

dependencies {
  implementation(libs.kotlinx.coroutines.core)
  implementation(libs.kotlinx.serialization.json)
  implementation(libs.mcp.kotlin.sdk.server)
  // CIO hosts the optional remote UI-builder Streamable HTTP endpoint (the MCP SDK owns the
  // protocol route); this dependency is what makes the module layer 2.
  implementation(libs.ktor.server.cio)
  // Okio-based file IO (`SystemFileSystem`) for descriptor reads + PNG/video byte reads.
  implementation(libs.composeai.common.io)
  implementation(libs.composeai.agent.grant.protocol)
  implementation(libs.composeai.ui.builder.protocol)

  // `api` for types on this module's public surface (`RenderSession`, `DaemonClient`,
  // `DaemonClientFactory`, protocol messages). Compiled against a compose-ai-tools release, so an
  // API must be released before it's usable here. Versions come from these platforms (see the
  // catalog's BOM block).
  api(platform(libs.composeai.tools.bom))
  api(platform(libs.composeai.contracts.bom))
  api(platform(libs.composeai.daemon.bom))
  api(libs.composeai.daemon.core)
  api(libs.composeai.render.session.api)
  api(libs.composeai.daemon.client)

  // Semantics diff engine + payload model for the `diff_semantics` tool.
  implementation(libs.composeai.data.layoutinspector.core)
  // Axis expansion + contact-sheet stitching behind the `render_matrix` tool, shared with the CLI's
  // offline `render-matrix` command so the two agree by construction.
  implementation(libs.composeai.render.matrix)
  // The design-guidelines engine behind `preview_guidelines_prompt` and `check_preview_guidelines`:
  // the same batching, prompt and verdict parsing the CLI's `compose-preview guidelines` runs.
  implementation(libs.composeai.design.guidelines)
  implementation(libs.composeai.design.guidelines.protocol)

  // See the `uiBuilderWeb` configuration above; a bare ZIP, so requested artifact-only.
  add("uiBuilderWeb", "${libs.composeai.ui.builder.web.get()}@zip")

  testImplementation(libs.junit)
  testImplementation(libs.truth)
  testImplementation(libs.kotlinx.coroutines.core)
  testImplementation(libs.ktor.server.test.host)
}

// JUnit 4 (unlike `:server`'s JUnit 5): these tests use Truth, and converting them is a separate
// change.
tasks.withType<Test>().configureEach {
  // `-Pmcp.real=true` enables `RealMcpEndToEndTest`; `-Pmcp.workdir=<path>` points it at another
  // checkout (default: the test's working directory).
  val mcpReal = providers.gradleProperty("mcp.real").orNull == "true"
  systemProperty("composeai.mcp.real", mcpReal.toString())
  providers.gradleProperty("mcp.workdir").orNull?.let {
    systemProperty("composeai.mcp.workdir", it)
  }
  // `-Pmcp.editLoop=true` runs `EditLoopIntegrationTest` on a real Android fixture (copies
  // `src/editLoopFixture` and the wrapper) and writes timings and work records to the report CI
  // uploads.
  val editLoop = providers.gradleProperty("mcp.editLoop").orNull == "true"
  systemProperty("composeai.mcp.editLoop", editLoop.toString())
  if (editLoop) {
    // The CI log is where a failing edit loop is read: the full assertion (which tasks, which
    // cycle) and the report the test prints, not just the exception class.
    testLogging {
      exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
      showStandardStreams = true
    }
  }
  systemProperty("composeai.mcp.repoRoot", rootDir.absolutePath)
  // `ANDROID_HOME` otherwise; for a launcher that does not pass the environment through.
  providers.gradleProperty("mcp.androidSdk").orNull?.let {
    systemProperty("composeai.mcp.androidSdk", it)
  }
  systemProperty(
    "composeai.mcp.editLoopReport",
    layout.buildDirectory.file("edit-loop/edit-loop-report.json").get().asFile.absolutePath,
  )
}

// `:mcp` must not pull `gradle-tooling-api`, directly or transitively: the Tooling API stays off
// this repository (AGENTS.md, the layer rule); a server needing a Gradle build asks
// compose-ai-tools across a process boundary.
abstract class CheckMcpToolingApiBoundary : DefaultTask() {
  @get:org.gradle.api.tasks.Classpath abstract val runtimeClasspath: ConfigurableFileCollection

  @TaskAction
  fun check() {
    val forbidden =
      runtimeClasspath.files
        .map { it.name }
        .filter { it.startsWith("gradle-tooling-api") && it.endsWith(".jar") }
        .sorted()
    check(forbidden.isEmpty()) {
      ":mcp must not depend on gradle-tooling-api. Driving a build is layer-1 behaviour and this " +
        "repository asks compose-ai-tools for it across a process boundary — see AGENTS.md and " +
        "docs/design/REPOSITORY_LAYERS.md. Found on runtimeClasspath: " +
        forbidden.joinToString(", ")
    }
  }
}

val checkMcpToolingApiBoundary =
  tasks.register<CheckMcpToolingApiBoundary>("checkMcpToolingApiBoundary") {
    description = "Fails if gradle-tooling-api leaks onto :mcp's runtime classpath."
    group = "verification"
    runtimeClasspath.from(configurations.named("runtimeClasspath"))
  }

// Also on `test`, because that is what CI runs.
tasks.named("check") { dependsOn(checkMcpToolingApiBoundary) }

tasks.named("test") { finalizedBy(checkMcpToolingApiBoundary) }
