package ee.schimke.composeai.mcp

import java.util.Properties

/**
 * Version this module reports in the MCP `initialize` handshake's `serverInfo.version` — for the
 * stdio server, the Storybook-compatibility profile, and the shared UI-builder adapter.
 *
 * Resolved from this module's own `mcp-version.properties`, generated by its build from
 * `project.version` the same way `:server` generates `serve-version.properties` for `SERVE_VERSION`
 * (see `ServeVersion.kt`). Falls back to `"dev"` when the resource is missing — a classpath built
 * outside this module's Gradle build (an IDE run configuration, an ad-hoc `java -cp`) rather than a
 * reason to crash a client's `initialize` call.
 */
internal val MCP_VERSION: String by lazy {
  val props = Properties()
  val stream =
    object {}
      .javaClass
      .classLoader
      .getResourceAsStream("ee/schimke/composeai/mcp/mcp-version.properties")
  if (stream == null) {
    "dev"
  } else {
    stream.use { props.load(it) }
    props.getProperty("version") ?: "dev"
  }
}
