#!/usr/bin/env python3
"""Compile selected upstream modules into an opt-in, workspace-local Maven repository."""

import argparse
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import uuid
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]


def stage(checkout: Path, modules: list[str], output: Path) -> Path:
    checkout = checkout.resolve(strict=True)
    if not (checkout / "gradlew").is_file():
        raise ValueError(f"No Gradle wrapper in {checkout}")
    if not modules or any(not re.fullmatch(r"(:[A-Za-z0-9_-]+)+", m) for m in modules):
        raise ValueError("Name one or more Gradle project paths, such as :ui-builder-protocol")
    # These two upstream publications compile the same generator sources. The server carries
    # both, so replacing only screen-model would let classpath order pick an older generator.
    generator_projects = {":screen-model", ":gradle-plugin:preview-discovery"}
    if generator_projects.intersection(modules) and (checkout / "gradle-plugin/preview-discovery").is_dir():
        modules = sorted(set(modules) | generator_projects)

    output = output.resolve()
    repository = output / "repository"
    repository.mkdir(parents=True, exist_ok=True)
    # Every run has a fresh identity, including uncommitted source edits. Gradle cannot reuse an
    # earlier snapshot's bytes, and a failed publish cannot replace a previously selected build.
    version = f"0.0.0-local-{uuid.uuid4().hex}-SNAPSHOT"
    env = dict(os.environ, PLUGIN_VERSION=version, CORE_LINE_VERSION=version)
    command = [
        str(checkout / "gradlew"), "--no-daemon", "--no-configuration-cache",
        "--init-script", str(ROOT / "scripts/local-dependencies/publish.init.gradle"),
        f"-PuiBuilderLocalRepository={repository}",
        *[f"{module}:publishAllPublicationsToUiBuilderLocalRepository" for module in modules],
    ]
    subprocess.run(command, cwd=checkout, env=env, check=True)

    # Read actual publications, including KMP target modules, rather than guessing artifactIds
    # from Gradle project paths. POM filenames may be timestamped for Maven snapshots.
    coordinates = set()
    ns = {"m": "http://maven.apache.org/POM/4.0.0"}
    for pom in repository.glob(f"**/{version}/*.pom"):
        model = ET.parse(pom).getroot()
        parts = [model.findtext(f"m:{key}", namespaces=ns) for key in ("groupId", "artifactId", "version")]
        if not all(parts) or parts[2] != version:
            raise ValueError(f"Unexpected publication identity in {pom}: {parts}")
        coordinates.add(":".join(parts))
    if not coordinates:
        raise ValueError("Gradle completed without staging any Maven publications")

    manifest = output / "local-dependencies.properties"
    existing = {}
    if manifest.exists():
        for line in manifest.read_text().splitlines():
            if line.startswith("coordinates="):
                for coordinate in line.removeprefix("coordinates=").split(","):
                    group, artifact, old_version = coordinate.split(":")
                    existing[f"{group}:{artifact}"] = old_version
    for coordinate in coordinates:
        group, artifact, staged_version = coordinate.split(":")
        existing[f"{group}:{artifact}"] = staged_version

    provenance = output / "builds" / f"{version}.json"
    provenance.parent.mkdir(parents=True, exist_ok=True)
    git_head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=checkout, text=True, capture_output=True)
    git_status = subprocess.run(["git", "status", "--porcelain"], cwd=checkout, text=True, capture_output=True)
    provenance.write_text(json.dumps({
        "checkout": str(checkout), "head": git_head.stdout.strip(),
        "status": git_status.stdout, "modules": modules, "coordinates": sorted(coordinates),
    }, indent=2) + "\n")

    # The repository is relative to the manifest, so spaces and non-ASCII checkout paths need no
    # Java properties escaping. Replace atomically only after a successful upstream build.
    temporary = output / f".{version}.properties"
    temporary.write_text(
        "# Generated by scripts/stage-local-dependency.py; opt in with -PlocalDependencies=<this file>\n"
        "repository=repository\ncoordinates="
        + ",".join(f"{module}:{v}" for module, v in sorted(existing.items())) + "\n"
    )
    temporary.replace(manifest)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkout", type=Path, required=True)
    parser.add_argument("--module", action="append", required=True, help="Repeat for dependent projects")
    parser.add_argument("--output", type=Path, default=ROOT / "build/local-dependencies")
    args = parser.parse_args()
    manifest = stage(args.checkout, args.module, args.output)
    print(f"\nLocal dependencies staged. Build the existing application with:\n"
          f"./gradlew {shlex.quote('-PlocalDependencies=' + str(manifest))} "
          ":ui-builder:jvmTest :ui-builder:compileKotlinWasmJs")


if __name__ == "__main__":
    main()
