package ee.schimke.composeai.cli.serve

import java.util.Properties

/**
 * Version the preview server reports to its clients — in `/version`, in the session-viewer
 * handshake, and in the bug-report bundle.
 *
 * Deliberately the server's own constant rather than `:cli`'s `SERVE_VERSION`, even though the two
 * resolve to the same string today because `serve` still ships inside the CLI jar. #3824 splits the
 * server into its own build, and on that day "the version the server reports" and "the version of
 * the CLI that happens to launch it" stop being the same fact: a client talking to a deployed
 * server is asking what the *server* is, and the seam register counted every one of these reads as
 * the server reaching into the CLI for an answer only the server has.
 *
 * Resolved from the server module's own `serve-version.properties`, generated by its build the same
 * way `:cli` generates `cli-version.properties`. Both derive from `project.version`, so the two
 * agree today and neither reads the other; when the server ships from its own repo they stop
 * agreeing and nothing here changes.
 */
internal val SERVE_VERSION: String by lazy {
  val props = Properties()
  val stream =
    object {}
      .javaClass
      .classLoader
      .getResourceAsStream("ee/schimke/composeai/cli/serve/serve-version.properties")
      ?: error("serve-version.properties missing from the preview server jar")
  stream.use { props.load(it) }
  props.getProperty("version") ?: error("version property missing from cli-version.properties")
}
