package ee.schimke.composeai.cli.serve

import java.awt.Font
import java.awt.Graphics2D
import java.awt.geom.RoundRectangle2D
import java.awt.image.BufferedImage
import java.security.MessageDigest
import java.util.Optional
import java.util.concurrent.ConcurrentHashMap
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt

/**
 * The **link-unfurl card**: a 1200×630 picture of what a page is, drawn once per distinct set of
 * inputs and served immutable off `/social/`.
 *
 * ## Why a drawn card and not a render
 *
 * The front door used to advertise the featured catalog's *own hero render* to unfurlers — whatever
 * preview happened to sit in the first card of the first section. Two things were wrong with that,
 * and neither is fixable by picking a different preview:
 *
 * * **Shape.** A catalog hero is a phone screenshot: `compose-m3`'s is 1078×2399, an aspect of
 *   1:2.23. Every unfurler lays a large-image card out at roughly 1.91:1, so a portrait tower is
 *   centre-cropped to a horizontal band (X, Facebook), demoted to a small thumbnail (Slack), or
 *   letterboxed. On this particular render the surviving band was the *empty* lower half of an app
 *   scaffold — a link to the catalog index unfurled as a strip of blank dark pixels.
 * * **Subject.** A picture of one AppScaffold sample says nothing about a server publishing 21
 *   catalogs. It carried no product mark, no name, and no count, so the card was unrecognisable as
 *   this site even when it did crop well.
 *
 * A card drawn at exactly the aspect the medium asks for solves both: it is 1200×630 (1.90:1, the
 * size Open Graph documents and every consumer treats as native), it says what the page is in
 * words, and it *still* shows the real renders — as thumbnails inside a layout, where portrait
 * artwork is an asset rather than a problem.
 *
 * ## Why it is baked rather than committed
 *
 * The card's content is live server state — which catalogs are published, how many previews they
 * carry, what their heroes currently look like. A committed PNG would be stale the moment a catalog
 * was added, and would have to be regenerated by hand for every operator running their own server
 * with their own catalogs. So it is drawn from the same [ServeHeroImages.Hero] thumbnails the front
 * door already baked (no new decode of a full render, no render permit) and cached like they are:
 *
 * * **Content-addressed.** The file name is a hash of the baked bytes, so the response is
 *   `immutable` and a republished catalog simply gets a new URL. This matters more here than for a
 *   hero: unfurlers cache aggressively and by URL, and several never revalidate at all, so a card
 *   whose URL outlived its pixels would be pinned in Slack's cache indefinitely.
 * * **Memoised by input, not by page.** The key is the text plus the heroes' own content hashes
 *   ([cacheKey]), so the front door and a catalog landing that happen to describe the same thing
 *   share one bake, and a hero that hasn't changed doesn't trigger one.
 *
 * Both maps are bounded by (catalogs × republishes) like [ServeHeroImages]'s, which is why nothing
 * is evicted — and why the *subtitle a caller passes must not carry a per-request value*. Anything
 * that changes as often as a view counter would mint a fresh card per visit and turn this into a
 * leak; [ServeSocialCard.Spec] documents that constraint where callers will read it.
 */
internal class ServeSocialCard {

  /** One baked card: the bytes to serve, how to name and validate them, and the declared size. */
  data class Card(
    val bytes: ByteArray,
    /** Content hash + `.png`; the `/social/{name}` segment and the ETag. */
    val fileName: String,
    val etag: String,
    /**
     * The catalogs allowed to serve this card; empty for the front door's own.
     *
     * A **set**, not one owner: the file name is a content hash, so two catalogs that draw an
     * identical card — same title, same preview count, same hero bytes — collapse onto one entry.
     * Recording a single owner cached the second catalog's card under the first's name, and the
     * second site then 404'd the very card its own `og:image` advertised. Every spec that produced
     * these bytes is remembered instead, so a shared hash serves for all of them and none of their
     * neighbours. See [Spec.system].
     */
    val systems: Set<String> = emptySet(),
  ) {
    /** Always [WIDTH] — declared so callers fill `og:image:width` from the card, not a constant. */
    val width: Int = WIDTH

    /** Always [HEIGHT]. */
    val height: Int = HEIGHT

    // See [ServeHeroImages.Hero]: identity equality. Cards are compared by hash, never by content,
    // and a data class over a ByteArray would otherwise generate an array-identity equals.
    override fun equals(other: Any?): Boolean = this === other

    override fun hashCode(): Int = System.identityHashCode(this)
  }

  /**
   * What a card should say and show.
   *
   * [title] and [subtitle] must be **stable for as long as the page is** — they are part of the
   * cache key (see the class doc). A count of published catalogs or previews is fine; a view
   * counter, a timestamp, or anything else that moves per request is not: it would mint a card per
   * visit, none of which is ever evicted.
   *
   * [heroes] are the already-baked front-door thumbnails, in the order they should appear. At most
   * [MAX_HEROES] are drawn, for the reason given there. An empty list is valid and lays the text
   * across the full width, which is the right card for a server publishing nothing yet.
   */
  data class Spec(
    val title: String,
    val subtitle: String,
    val heroes: List<ServeHeroImages.Hero> = emptyList(),
    /**
     * The catalog this card depicts, or null for the front door's whole-server card.
     *
     * Recorded so a **top-level site** ([ServeSites]) can refuse a neighbour's card. `/social/` is
     * deliberately ungated — a link unfurler never replays a page's token — and the file name is a
     * content hash, so a hash published by one catalog's `og:image` on the main host could be
     * fetched back through a one-catalog hostname and answer with that other catalog's title and
     * thumbnails. Ownership travels with the card rather than being re-derived at request time,
     * because by then the bytes are all that is left.
     */
    val system: String? = null,
  )

  private val byFileName = ConcurrentHashMap<String, Card>()

  /**
   * Memo of the bake, keyed by [cacheKey]. A failed bake caches its failure so it isn't retried.
   */
  private val baked = ConcurrentHashMap<String, Optional<Card>>()

  /** The card for [spec], drawing it on first sight. Null only if PNG encoding fails. */
  fun cardFor(spec: Spec): Card? {
    val key = cacheKey(spec)
    baked[key]?.let {
      return it.orElse(null)
    }
    val card = draw(spec)
    baked[key] = Optional.ofNullable(card)
    return card
  }

  /** The baked card a `/social/{fileName}` request names, or null when unknown. */
  fun byFileName(fileName: String): Card? = byFileName[fileName]

  /**
   * The memo key: the text plus each hero's **content hash**. Hashes rather than object identity
   * because a catalog refresh installs fresh [ServeHeroImages.Hero] objects whose bytes are usually
   * unchanged, and re-baking an identical card on every refresh would grow [byFileName] for
   * nothing. The unit separator can't occur in a title (it is not text anyone can type) so no field
   * can be confused with another's.
   */
  private fun cacheKey(spec: Spec): String =
    (listOf(spec.system.orEmpty(), spec.title, spec.subtitle) +
        spec.heroes.take(MAX_HEROES).map { it.fileName })
      .joinToString(FIELD_SEPARATOR)

  /** Draw [spec] and register it under its content hash. Visible only for tests. */
  internal fun draw(spec: Spec): Card? {
    val image = BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_RGB)
    val g = image.createGraphics()
    try {
      ServeBrand.quality(g)
      g.color = ServeBrand.BG
      g.fillRect(0, 0, WIDTH, HEIGHT)
      val heroes =
        spec.heroes.take(MAX_HEROES).mapNotNull { hero -> ServeBrand.decodePng(hero.bytes) }
      // The text column narrows only when there is art to sit beside; a card with no thumbnails
      // spends the whole width on words rather than leaving a hole where the art would have been.
      val textWidth = if (heroes.isEmpty()) WIDTH - PAD * 2 else TEXT_COLUMN
      drawBrandRow(g)
      drawText(g, spec, textWidth)
      if (heroes.isNotEmpty()) drawHeroes(g, heroes)
    } finally {
      g.dispose()
    }
    val bytes = ServeBrand.encodePng(image) ?: return null
    val hash = sha256Hex(bytes).take(HASH_CHARS)
    val card =
      Card(
        bytes = bytes,
        fileName = "$hash.png",
        etag = "\"$hash\"",
        systems = setOfNotNull(spec.system),
      )
    // Two specs that draw to identical bytes share the URL, so the bytes are already right and
    // only the OWNERS have to accumulate: a card drawn identically for a second catalog must stay
    // serveable by that catalog's site too, which first-wins (`putIfAbsent`) silently prevented —
    // the second site 404'd the very card its own og:image advertised.
    return byFileName.compute(card.fileName) { _, existing ->
      when {
        existing == null -> card
        // Identical spec, identical owner: the registration already there IS the right answer, and
        // handing back the same instance is what callers (and ServeSocialCardTest) rely on.
        card.systems.all { it in existing.systems } -> existing
        else -> existing.copy(systems = existing.systems + card.systems)
      }
    } ?: card
  }

  /** The product mark and wordmark, top-left — the same pair the site header opens with. */
  private fun drawBrandRow(g: Graphics2D) {
    ServeBrand.drawMark(g, PAD.toDouble(), PAD.toDouble(), MARK_SIZE.toDouble())
    g.font = ServeBrand.font(26f, medium = true)
    g.color = ServeBrand.FG_MUTED
    val metrics = g.fontMetrics
    // Optically centred on the mark rather than sharing its baseline: the wordmark is half the
    // mark's height, and a shared baseline would hang it off the bottom of the circle.
    val baseline = PAD + MARK_SIZE / 2f + (metrics.ascent - metrics.descent) / 2f
    g.drawString("compose-preview", (PAD + MARK_SIZE + 18).toFloat(), baseline)
  }

  /**
   * The headline and its supporting line, as a block vertically centred in the space under the
   * brand row.
   *
   * The headline **shrinks to fit** rather than being truncated: catalog titles are operator data
   * and range from "Wear M3" to a four-word product name, and a card that clipped one would be
   * worse than a card that set it a size smaller. Only when the smallest size still overflows two
   * lines does it ellipsize — at that point the text is long enough that no size would have helped.
   */
  private fun drawText(g: Graphics2D, spec: Spec, width: Int) {
    val headline =
      HEADLINE_SIZES.firstNotNullOfOrNull { size ->
        val font = ServeBrand.font(size, medium = true)
        wrap(g, spec.title, font, width, MAX_HEADLINE_LINES)?.let { lines ->
          Laid(font, lines, size)
        }
      }
        ?: ServeBrand.font(HEADLINE_SIZES.last(), medium = true).let { font ->
          Laid(
            font,
            ellipsize(g, spec.title, font, width, MAX_HEADLINE_LINES),
            HEADLINE_SIZES.last(),
          )
        }
    val subFont = ServeBrand.font(SUBTITLE_SIZE, medium = false)
    val subLines =
      wrap(g, spec.subtitle, subFont, width, MAX_SUBTITLE_LINES)
        ?: ellipsize(g, spec.subtitle, subFont, width, MAX_SUBTITLE_LINES)

    val headlineLead = headline.size * LEADING
    val subLead = SUBTITLE_SIZE * LEADING
    val blockHeight =
      headline.lines.size * headlineLead +
        (if (subLines.isEmpty()) 0f else GAP + subLines.size * subLead)
    val bandTop = PAD + MARK_SIZE + BRAND_GAP
    val bandHeight = HEIGHT - PAD - bandTop
    var y = bandTop + max(0f, (bandHeight - blockHeight) / 2f)

    g.color = ServeBrand.ACCENT
    g.fillRect(
      PAD,
      (y - ACCENT_RULE_GAP - ACCENT_RULE_H).roundToInt(),
      ACCENT_RULE_W,
      ACCENT_RULE_H,
    )

    g.font = headline.font
    g.color = ServeBrand.FG
    headline.lines.forEach { line ->
      y += headline.font.size2D
      g.drawString(line, PAD.toFloat(), y)
      y += headlineLead - headline.font.size2D
    }
    if (subLines.isEmpty()) return
    y += GAP
    g.font = subFont
    g.color = ServeBrand.FG_MUTED
    subLines.forEach { line ->
      y += SUBTITLE_SIZE
      g.drawString(line, PAD.toFloat(), y)
      y += subLead - SUBTITLE_SIZE
    }
  }

  /** A headline resolved to the largest size that fits, with the lines that size produced. */
  private data class Laid(val font: Font, val lines: List<String>, val size: Float)

  /**
   * The thumbnails, bottom-aligned in a row down the right of the card, each on its own tonal
   * panel.
   *
   * Bottom-aligned rather than centred because the artwork is device screenshots of differing
   * aspect — a phone beside a watch face — and standing them on a shared floor reads as a shelf of
   * devices, while centring them reads as a mistake. The panel is what makes a dark screenshot
   * legible at all: without it a dark render on the dark card has no edge, and the phone appears to
   * bleed into the background.
   */
  private fun drawHeroes(g: Graphics2D, heroes: List<BufferedImage>) {
    val columnX = PAD + TEXT_COLUMN + COLUMN_GAP
    val columnWidth = WIDTH - PAD - columnX
    val slotWidth = (columnWidth - HERO_GAP * (heroes.size - 1)) / heroes.size
    val maxImageW = min(slotWidth - PANEL_INSET * 2, MAX_HERO_WIDTH)
    val maxImageH = HEIGHT - PAD * 2 - PANEL_INSET * 2
    val floor = HEIGHT - PAD - PANEL_INSET
    heroes.forEachIndexed { index, hero ->
      // Never past 1.0: a hero is baked at up to 480px on its longest edge, so fitting a *square*
      // one to the card's height would blow a 480² watch face up to fill half the card — twice the
      // area of a phone standing beside it, and visibly soft. Capped, the shelf reads as devices at
      // their own sizes rather than as one image stretched.
      val fit = minOf(maxImageW.toDouble() / hero.width, maxImageH.toDouble() / hero.height, 1.0)
      val w = max(1, (hero.width * fit).roundToInt())
      val h = max(1, (hero.height * fit).roundToInt())
      val x = columnX + index * (slotWidth + HERO_GAP) + (slotWidth - w) / 2
      val y = floor - h
      val panel =
        RoundRectangle2D.Double(
          (x - PANEL_INSET).toDouble(),
          (y - PANEL_INSET).toDouble(),
          (w + PANEL_INSET * 2).toDouble(),
          (h + PANEL_INSET * 2).toDouble(),
          PANEL_RADIUS,
          PANEL_RADIUS,
        )
      g.color = ServeBrand.PANEL
      g.fill(panel)
      g.color = ServeBrand.BORDER
      g.draw(panel)
      // Clip the render to a soft corner so it sits *in* the panel rather than on top of it.
      val clip = g.clip
      g.clip(
        RoundRectangle2D.Double(
          x.toDouble(),
          y.toDouble(),
          w.toDouble(),
          h.toDouble(),
          IMAGE_RADIUS,
          IMAGE_RADIUS,
        )
      )
      g.drawImage(hero, x, y, w, h, null)
      g.clip = clip
    }
  }

  /**
   * [text] broken onto at most [maxLines] lines that each fit [width], or **null** when it doesn't
   * fit — the signal [drawText] uses to try the next size down.
   *
   * Breaks on spaces only. A word longer than the line is left to overflow the measurement and so
   * fails the fit, which is the honest answer: the caller's next smaller size may well take it, and
   * mid-word hyphenation of a product name would be worse than either outcome.
   */
  private fun wrap(
    g: Graphics2D,
    text: String,
    font: Font,
    width: Int,
    maxLines: Int,
  ): List<String>? {
    val metrics = g.getFontMetrics(font)
    val lines = mutableListOf<String>()
    var line = StringBuilder()
    for (word in text.split(' ').filter { it.isNotEmpty() }) {
      val candidate = if (line.isEmpty()) word else "$line $word"
      if (metrics.stringWidth(candidate) <= width) {
        line = StringBuilder(candidate)
        continue
      }
      if (line.isEmpty()) return null // A single word wider than the column.
      lines += line.toString()
      if (lines.size == maxLines) return null
      line = StringBuilder(word)
      if (metrics.stringWidth(word) > width) return null
    }
    if (line.isNotEmpty()) lines += line.toString()
    return lines.takeIf { it.isNotEmpty() && it.size <= maxLines }
  }

  /**
   * Last resort for text that fits at no size: fill [maxLines] and cut the final one with an
   * ellipsis. Character-wise, because by definition word-wrapping has already failed here.
   */
  private fun ellipsize(
    g: Graphics2D,
    text: String,
    font: Font,
    width: Int,
    maxLines: Int,
  ): List<String> {
    val metrics = g.getFontMetrics(font)
    val lines = mutableListOf<String>()
    var rest = text
    while (rest.isNotEmpty() && lines.size < maxLines) {
      val last = lines.size == maxLines - 1
      var cut = rest.length
      while (
        cut > 1 &&
          metrics.stringWidth(rest.take(cut) + if (last && cut < rest.length) "…" else "") > width
      ) {
        cut--
      }
      val head = rest.take(cut)
      lines += if (last && cut < rest.length) "$head…" else head
      rest = rest.drop(cut)
    }
    return lines
  }

  companion object {
    /**
     * The card's pixel size. 1200×630 is what the Open Graph documentation names, what X's
     * `summary_large_image` is laid out at, and what Slack, Discord, LinkedIn and iMessage all
     * treat as the native shape — so the card is never cropped by anyone. Its 1.90:1 aspect is also
     * comfortably inside the band [ServeWeb] will still claim a large card for.
     */
    const val WIDTH = 1200

    const val HEIGHT = 630

    /** The URL prefix baked cards are served under. See [ServeHttpServer]'s `/social/` route. */
    const val PATH_PREFIX = "/social"

    /**
     * Thumbnails drawn at most.
     *
     * Two, not more, because the artwork is *portrait* and the card is wide: three phones side by
     * side have to shrink to a third of the art column's width each, which at the ~500px a chat
     * client actually renders the card at leaves each one about 60px wide — a grey sliver rather
     * than a recognisable UI. Two fill the card's full height at their natural size and still say
     * "there is more than one catalog here", which is all the artwork is being asked to say.
     */
    const val MAX_HEROES = 2

    /**
     * Widest a single thumbnail is drawn, matching [ServeHeroImages.DISPLAY_CAP] — the CSS size the
     * front door lays the same image out at. Without it a square hero (a watch face bakes to 480²)
     * fits the card's *height* and takes over the composition; with it, a phone and a watch stand
     * beside each other at the relative sizes they have in the world.
     */
    private const val MAX_HERO_WIDTH = ServeHeroImages.DISPLAY_CAP

    private const val PAD = 64
    private const val MARK_SIZE = 56

    /** Space between the brand row and the text block below it. */
    private const val BRAND_GAP = 40

    /** Width of the words column when there is artwork beside it. */
    private const val TEXT_COLUMN = 520

    /** Gutter between the text column and the artwork. */
    private const val COLUMN_GAP = 40

    private const val HERO_GAP = 20
    private const val PANEL_INSET = 12
    private const val PANEL_RADIUS = 20.0
    private const val IMAGE_RADIUS = 10.0

    /** Headline sizes tried largest-first; the first that fits [MAX_HEADLINE_LINES] wins. */
    private val HEADLINE_SIZES = listOf(66f, 58f, 50f, 42f, 36f)

    private const val MAX_HEADLINE_LINES = 2
    private const val SUBTITLE_SIZE = 28f
    private const val MAX_SUBTITLE_LINES = 2

    /** Line height as a multiple of the font size. */
    private const val LEADING = 1.18f

    /** Space between the headline block and the subtitle. */
    private const val GAP = 26f

    private const val ACCENT_RULE_W = 72
    private const val ACCENT_RULE_H = 5
    private const val ACCENT_RULE_GAP = 28

    private const val HASH_CHARS = 16

    /**
     * Separates the fields of [cacheKey]. ASCII unit separator: it is not text anyone can type into
     * a catalog title, so no combination of title and subtitle can collide with a different pair.
     */
    private const val FIELD_SEPARATOR = "\u001F"

    private fun sha256Hex(bytes: ByteArray): String =
      MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }
  }
}
