package ee.schimke.composeai.cli.serve

/** A project workspace around the existing editor. User content enters the DOM only as text. */
internal fun uiBuilderProjectsPage(): String =
  """
  <!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UI Builder projects</title>
  <style>
  :root{color-scheme:light dark;font:16px system-ui;line-height:1.5}body{max-width:1100px;margin:40px auto;padding:0 24px;background:light-dark(#faf9f6,#171918);color:light-dark(#222,#eee)}a{color:light-dark(#14654c,#8ee3bf)}header{display:flex;justify-content:space-between;align-items:center;gap:24px}h1{font-size:2.2rem;letter-spacing:-.04em}h2{margin-top:0}.intro{max-width:680px;color:light-dark(#59635e,#acb7b0)}.layout{display:grid;grid-template-columns:260px 1fr;gap:24px}section,article,details{border:1px solid light-dark(#d7dfd9,#3b4640);border-radius:12px;padding:20px;margin:16px 0;background:light-dark(#fff,#202521)}button,input,select,textarea{font:inherit;border:1px solid #80978b;border-radius:6px;padding:8px}button{cursor:pointer}button:disabled{cursor:wait;opacity:.5}input,textarea{box-sizing:border-box;width:100%;margin:4px 0 12px}textarea{min-height:150px;font-family:monospace;font-size:13px}label{display:block}button.primary{background:#14654c;color:white;border-color:#14654c}nav button{display:block;width:100%;text-align:left;margin:8px 0}.meta{font-size:.9rem;color:light-dark(#59635e,#acb7b0)}.badge{display:inline-block;border-radius:20px;padding:3px 12px;background:light-dark(#e3f3eb,#293e33)}.actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center}pre{overflow:auto;max-height:350px;font-size:12px;white-space:pre-wrap}#status{min-height:24px}#status.error{color:light-dark(#a12d22,#ff9f95)}[hidden]{display:none!important}@media(max-width:700px){.layout{grid-template-columns:1fr}header{align-items:flex-start;flex-direction:column}}
  </style></head><body>
  <header><h1>UI Builder projects</h1><div class="actions"><a id="designs" href="/ui-builder/designs">All designs</a><a href="/auth/github/start?return=%2Fui-builder%2Fprojects">Sign in</a></div></header>
  <p class="intro">Keep an app’s design files, shared resources and collaborators together. Connected repositories stay canonical; edits are saved here until you propose a pull request.</p>
  <p id="status" role="status" aria-live="polite"></p><div class="layout"><aside><nav id="projects" aria-label="Projects"></nav>
  <details><summary>Create project</summary><form id="create"><label>Project ID<input name="id" required pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,63}"></label><label>Name<input name="name" required maxlength="160"></label><label>GitHub repository (optional)<input name="repository" placeholder="owner/app"></label><label>Branch<input name="branch" placeholder="Default branch"></label><label>Project root<input name="root" value="ui-builder"></label><label>GitHub token for private repository (optional)<input name="credential" type="password" autocomplete="off"></label><button class="primary">Create / connect</button></form></details></aside><main id="workspace"><section><h2>Your app’s design workspace</h2><p>Select a project or create one. A repository with a project manifest or .uid files can be connected directly.</p></section></main></div>
  <script>
  (function(){
  'use strict';
  const q=new URLSearchParams(location.search),suffix=q.has('token')?'?token='+encodeURIComponent(q.get('token')):'';
  document.getElementById('designs').href+=suffix;
  const api='/api/ui-builder/v1/projects',status=document.getElementById('status'),workspace=document.getElementById('workspace');let current=null,review=null;
  function node(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n;}
  function notice(text,error){status.textContent=text;status.className=error?'error':'';}
  async function request(path,method='GET',body,credential){const headers={};if(body)headers['Content-Type']='application/json';if(credential)body={...body,githubToken:credential};const r=await fetch(api+path+suffix,{method,headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
  async function run(action){try{notice('Working…');await action();notice('Saved.');}catch(e){notice(e.message,true);}}
  async function load(){const items=await request('');const nav=document.getElementById('projects');nav.replaceChildren();items.forEach(p=>{const b=node('button',p.name,nav);b.onclick=()=>run(async()=>{q.delete('design');show(await request('/'+encodeURIComponent(p.id)));});});}
  function field(form,label,name,value='',type='text'){const l=node('label',label,form),i=node(type==='textarea'?'textarea':'input',undefined,l);i.name=name;if(type!=='textarea')i.type=type;i.value=value;return i;}
  function endpoint(){return '/'+encodeURIComponent(current.id);}
  function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=node('a');a.href=url;a.download=name.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function show(p){current=p;review=null;q.set('project',p.id);history.replaceState(null,'','?'+q.toString());workspace.replaceChildren();
  const head=node('section',undefined,workspace);node('h2',p.name,head);node('span',p.source?'GitHub-backed project · Working copy':'Hosted project',head).className='badge';
  if(p.source){node('p','Home: '+p.source.repository+' · '+p.source.branch+' · '+(p.source.root||'/'),head).className='meta';node('p','Loaded from '+p.source.baseCommit.slice(0,12)+'. Autosave keeps edits here; publishing opens a pull request.',head).className='meta';const a=node('a','Open repository home',head);a.href='https://github.com/'+p.source.repository+'/tree/'+encodeURIComponent(p.source.branch)+(p.source.root?'/'+p.source.root:'');a.rel='noreferrer';}
  node('p','Project owner: '+p.owner,head).className='meta';
  const selected=q.get('design'),selectedFile=p.files.find(f=>Object.values(f.designs||{}).includes(selected));
  if(selectedFile){const sourceId=Object.keys(selectedFile.designs).find(k=>selectedFile.designs[k]===selected),home=(selectedFile.homes||{})[sourceId];const panel=node('section',undefined,workspace);node('h2','Editing '+sourceId,panel);const canonical=home&&home.kind==='server'&&home.designId===selected;node('span',canonical?'Editing the canonical hosted design':'Editing a working copy',panel).className='badge';if(home)node('p',home.kind==='repo'?'Canonical home: repository '+(p.source?p.source.repository+' · ':'')+home.path:'Canonical home: '+home.url+' · '+home.designId,panel).className='meta';else node('p','Canonical home unknown. This project holds a copy.',panel).className='meta';const frame=node('iframe',undefined,panel);frame.title='UI Builder editor for '+sourceId;frame.src='/ui-builder/'+encodeURIComponent(selected)+suffix;frame.style.cssText='width:100%;height:75vh;border:0;margin-top:16px';}

  if(p.publication){const a=node('a','Open proposed changes',head);a.href=p.publication.url;a.rel='noreferrer';node('p','Proposed bytes are recorded. Further edits require another review.',head).className='meta';}
  const files=node('section',undefined,workspace);node('h2','Design files & shared resources',files);
  p.files.filter(f=>f.kind!=='manifest').forEach(f=>{const card=node('article',undefined,files);node('h3',f.path,card);node('p',f.kind==='design'?'Design file':f.kind+' · project resource',card).className='meta';const actions=node('div',undefined,card);actions.className='actions';Object.entries(f.designs||{}).forEach(([source,id])=>{const a=node('a','Open '+source,actions);const target=new URLSearchParams(q);target.set('project',p.id);target.set('design',id);a.href='/ui-builder/projects?'+target.toString();});const b=node('button','Download .uid / JSON',actions);b.onclick=()=>run(async()=>{const r=await request(endpoint()+'/review');download(f.path,r.files[f.path]);});
  if(f.kind!=='design'){const details=node('details',undefined,card);node('summary','Edit resource',details);const form=node('form',undefined,details);const content=field(form,'Resource JSON','content',f.working||f.original,'textarea');node('button','Save resource',form);form.onsubmit=e=>{e.preventDefault();run(async()=>{show(await request(endpoint()+'/files','PUT',{baseRevision:current.revision,fileId:f.id,path:f.path,kind:f.kind,content:content.value}));await load();});};}
  });
  const add=node('details',undefined,workspace);node('summary','Add a .uid file or shared resource',add);const form=node('form',undefined,add);field(form,'File ID','fileId');field(form,'Project-relative path','path');const kind=node('select',undefined,form);['design','components','tokens','themes'].forEach(k=>{const o=node('option',k,kind);o.value=k;});const upload=node('input',undefined,form);upload.type='file';upload.accept='.uid,.json';const content=field(form,'File JSON','content','','textarea');upload.onchange=async()=>{if(upload.files[0])content.value=await upload.files[0].text();};node('button','Add file',form);form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);run(async()=>{show(await request(endpoint()+'/files','PUT',{baseRevision:current.revision,fileId:d.get('fileId'),path:d.get('path'),kind:kind.value,content:content.value}));await load();});};
  const members=node('details',undefined,workspace);node('summary','Project sharing',members);node('p','Use authenticated actor IDs, for example github:username. Roles are VIEWER or EDITOR.',members);const mf=node('form',undefined,members);const memberText=field(mf,'Members JSON','members',JSON.stringify(p.members,null,2),'textarea');node('button','Save sharing',mf);mf.onsubmit=e=>{e.preventDefault();run(async()=>show(await request(endpoint()+'/members','PUT',{baseRevision:current.revision,members:JSON.parse(memberText.value)})));};
  const publish=node('section',undefined,workspace);node('h2',p.source?'Propose changes to GitHub':'Download project files',publish);const rb=node('button','Review saved files',publish);const result=node('div',undefined,publish);rb.onclick=()=>run(async()=>{review=await request(endpoint()+'/review');result.replaceChildren();node('p',p.source?review.changed.length+' files differ from the loaded source.':'These files contain the saved design revisions.',result);Object.entries(review.files).forEach(([path,text])=>{const detail=node('details',undefined,result);node('summary',path+(review.changed.includes(path)?' · changed':''),detail);node('pre',text,detail);const b=node('button','Download',detail);b.onclick=()=>download(path,text);});if(p.source){const pf=node('form',undefined,result);const token=field(pf,'GitHub write token · sent for this action only','credential','','password');node('button','Open pull request',pf).className='primary';pf.onsubmit=e=>{e.preventDefault();const credential=token.value;token.value='';run(async()=>{show(await request(endpoint()+'/publish','POST',{baseRevision:review.revision,reviewDigest:review.digest},credential));await load();});};}});
  }
  document.getElementById('create').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);const credential=d.get('credential');form.elements.credential.value='';run(async()=>{const p=await request('','POST',{id:d.get('id'),name:d.get('name'),repository:d.get('repository'),branch:d.get('branch'),root:d.get('root')},credential);await load();show(p);});};
  run(async()=>{await load();if(q.get('project'))show(await request('/'+encodeURIComponent(q.get('project'))));});
  })();
  </script></body></html>
  """
    .trimIndent()
